-- -*- lua -*---
-- paraview@5.9.1%gcc@12.2.0~advanced_debug~cuda~examples+hdf5~ipo+kits+mpi+opengl2~osmesa+plugins~python+python3+qt+shared build_system=cmake build_type=RelWithDebInfo patches=405d451 arch=linux-rocky8-zen3/nlfrs2e
--

whatis([[Name : paraview]])
whatis([[Version : 5.9.1]])
whatis([[Short description : ParaView is an open-source, multi-platform data analysis and visualization application.]])
whatis([[Configure options : -DVTK_OPENGL_HAS_OSMESA:BOOL=OFF -DVTK_USE_X:BOOL=ON -DPARAVIEW_INSTALL_DEVELOPMENT_FILES:BOOL=ON -DBUILD_TESTING:BOOL=OFF -DOpenGL_GL_PREFERENCE:STRING=LEGACY -DPARAVIEW_INITIALIZE_MPI_ON_CLIENT=OFF -DPARAVIEW_USE_QT:BOOL=ON -DPARAVIEW_BUILD_WITH_EXTERNAL=ON -DPARAVIEW_ENABLE_XDMF2:BOOL=OFF -DPARAVIEW_ENABLE_XDMF3:BOOL=OFF -DPARAVIEW_USE_VTKM:BOOL=OFF -DPARAVIEW_ENABLE_EXAMPLES:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_ParaView_cgns=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_glew=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_gl2ps=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_libharu=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_utf8=OFF -DPARAVIEW_QT_VERSION=5 -DPARAVIEW_USE_PYTHON:BOOL=ON -DPYTHON_EXECUTABLE:FILEPATH=/apps/spack/negishi/apps/python/3.9.15-gcc-12.2.0-yt34dlv/bin/python3.9 -DPARAVIEW_PYTHON_VERSION:STRING=3 -DPARAVIEW_USE_MPI:BOOL=ON -DMPIEXEC:FILEPATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-12.2.0-aqmmssy/bin/mpiexec -DMPI_CXX_COMPILER:PATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-12.2.0-aqmmssy/bin/mpic++ -DMPI_C_COMPILER:PATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-12.2.0-aqmmssy/bin/mpicc -DMPI_Fortran_COMPILER:PATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-12.2.0-aqmmssy/bin/mpif90 -DPARAVIEW_BUILD_SHARED_LIBS:BOOL=ON -DPARAVIEW_USE_CUDA:BOOL=OFF -DPARAVIEW_BUILD_WITH_KITS:BOOL=ON -DCMAKE_INSTALL_RPATH=/apps/spack/negishi/apps/paraview/5.9.1-gcc-12.2.0-nlfrs2e/lib:/apps/spack/negishi/apps/paraview/5.9.1-gcc-12.2.0-nlfrs2e/lib64:/apps/spack/negishi/apps/bzip2/1.0.8-gcc-12.2.0-qfrydcp/lib:/apps/spack/negishi/apps/expat/2.4.8-gcc-12.2.0-tk4jw74/lib:/apps/spack/negishi/apps/freetype/2.7.1-gcc-12.2.0-ajb5ez6/lib:/apps/spack/negishi/apps/hdf5/1.13.2-gcc-12.2.0-zzksp3u/lib:/apps/spack/negishi/apps/libogg/1.3.5-gcc-12.2.0-zylbmw3/lib:/apps/spack/negishi/apps/libpng/1.6.37-gcc-12.2.0-wojrvhx/lib:/apps/spack/negishi/apps/libtheora/1.1.1-gcc-12.2.0-lqlamhu/lib:/apps/spack/negishi/apps/libxml2/2.10.1-gcc-12.2.0-i4ywaof/lib:/apps/spack/negishi/apps/libxt/1.1.5-gcc-12.2.0-3wvjd4n/lib:/apps/spack/negishi/apps/lz4/1.9.4-gcc-12.2.0-zu3llyv/lib:/apps/spack/negishi/apps/netcdf-c/4.9.0-gcc-12.2.0-jytdgrw/lib:/apps/spack/negishi/apps/openmpi/4.1.4-gcc-12.2.0-aqmmssy/lib:/apps/spack/negishi/apps/qt/5.15.2-gcc-12.2.0-alngczo/lib:/apps/spack/negishi/apps/xz/5.2.6-gcc-12.2.0-3zpozay/lib:/apps/spack/negishi/apps/zlib/1.2.13-gcc-12.2.0-lcttzi4/lib:/apps/spack/negishi/apps/double-conversion/3.1.5-gcc-12.2.0-pgizjoo/lib64:/apps/spack/negishi/apps/jsoncpp/1.9.4-gcc-12.2.0-zdntqy4/lib64:/apps/spack/negishi/apps/libjpeg-turbo/2.1.3-gcc-12.2.0-m53dnnx/lib64:/apps/spack/negishi/apps/libtiff/4.4.0-gcc-12.2.0-v2e7go5/lib64:/apps/spack/negishi/apps/protobuf/3.11.4-gcc-12.2.0-23ztwhu/lib64:/apps/spack/negishi/apps/pugixml/1.11.4-gcc-12.2.0-mzkqq4i/lib64:/apps/spack/negishi/apps/python/3.9.15-gcc-12.2.0-yt34dlv/lib]])

help([[ParaView is an open-source, multi-platform data analysis and
visualization application.]])


depends_on("bzip2/1.0.8")
depends_on("hdf5/1.13.2")
depends_on("libtiff/4.4.0")
depends_on("libxml2/2.10.1")
depends_on("netcdf-c/4.9.0")
depends_on("openmpi/4.1.4")
depends_on("protobuf/3.11.4")
depends_on("qt/5.15.2")
depends_on("zlib/1.2.13")

local modroot="/apps/spack/negishi/apps/paraview/5.9.1-gcc-12.2.0-nlfrs2e"
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("CPATH", modroot.."/include", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/", ":")
prepend_path("PATH", modroot.."/./bin", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/./", ":")
prepend_path("XLOCALEDIR", "/apps/spack/negishi/apps/libx11/1.7.0-gcc-12.2.0-6knafhz/share/X11/locale", ":")
prepend_path("TCLLIBPATH", "/apps/spack/negishi/apps/tk/8.6.11-gcc-12.2.0-grmtwvp/lib", " ")
prepend_path("PYTHONPATH", modroot.."/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-matplotlib/3.6.2-gcc-12.2.0-sqed3n3/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-contourpy/1.0.5-gcc-12.2.0-43jwcfc/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-numpy/1.23.4-gcc-12.2.0-dpifjin/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-setuptools/63.0.0-gcc-12.2.0-vajju2b/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-cycler/0.11.0-gcc-12.2.0-orfm2lr/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-fonttools/4.37.3-gcc-12.2.0-5ono2sk/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-kiwisolver/1.3.2-gcc-12.2.0-5s6eew7/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-packaging/21.3-gcc-12.2.0-ii5fscs/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-pyparsing/3.0.9-gcc-12.2.0-gfcw6sp/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-pillow/9.2.0-gcc-12.2.0-hjiihto/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-python-dateutil/2.8.2-gcc-12.2.0-jqhsvfi/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-six/1.16.0-gcc-12.2.0-7swxztb/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-mpi4py/3.1.4-gcc-12.2.0-lt2qy5y/lib/python3.9/site-packages", ":")
prepend_path("XDG_DATA_DIRS", "/apps/spack/negishi/apps/gobject-introspection/1.72.0-gcc-12.2.0-hajvh65/share", ":")
prepend_path("GI_TYPELIB_PATH", "/apps/spack/negishi/apps/gobject-introspection/1.72.0-gcc-12.2.0-hajvh65/lib/girepository-1.0", ":")
prepend_path("XDG_DATA_DIRS", "/apps/spack/negishi/apps/harfbuzz/5.1.0-gcc-12.2.0-oertlfs/share", ":")
prepend_path("GI_TYPELIB_PATH", "/apps/spack/negishi/apps/harfbuzz/5.1.0-gcc-12.2.0-oertlfs/lib/girepository-1.0", ":")
setenv("ParaView_DIR", modroot)
setenv("PARAVIEW_VTK_DIR", modroot.."/lib64/cmake/paraview-5.9/vtk")
prepend_path("LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("PYTHONPATH", modroot.."/lib64/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", modroot.."/lib64/python3.9/site-packages/vtkmodules", ":")
setenv("PARAVIEW_HOME", modroot)
setenv("RCAC_PARAVIEW_ROOT", modroot)
setenv("RCAC_PARAVIEW_VERSION", "5.9.1")

