-- -*- lua -*-
-- Module file created by spack (https://github.com/spack/spack) on 2025-05-19 15:21:51.238569
--
-- openfoam@2312%gcc@14.2.0~int64~kahip~knl+metis+mgridgen~paraview+scotch+source~vtk~zoltan build_system=generic precision=dp arch=linux-rocky8-zen2/mjzfujh
--

whatis([[Name : openfoam]])
whatis([[Version : 2312]])
whatis([[Target : zen2]])
whatis([[Short description : OpenFOAM is a GPL-opensource C++ CFD-toolbox. This offering is supported by OpenCFD Ltd, producer and distributor of the OpenFOAM software via www.openfoam.com, and owner of the OPENFOAM trademark. OpenCFD Ltd has been developing and releasing OpenFOAM since its debut in 2004. ]])

help([[Name   : openfoam]])
help([[Version: 2312]])
help([[Target : zen2]])
help()
help([[OpenFOAM is a GPL-opensource C++ CFD-toolbox. This offering is supported
by OpenCFD Ltd, producer and distributor of the OpenFOAM software via
www.openfoam.com, and owner of the OPENFOAM trademark. OpenCFD Ltd has
been developing and releasing OpenFOAM since its debut in 2004.]])


-- depends_on("cgal/5.6")
depends_on("fftw/3.3.10")
depends_on("gcc/8.5.0")
depends_on("openmpi/5.0.5")

local modroot = "/apps/spack/bell-20250305/apps/openfoam/2312-gcc-14.2.0-mjzfujh"
local user = os.getenv("USER")
local userhome = os.getenv("HOME")

prepend_path("PATH", modroot.."/bin", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/.", ":")
prepend_path("ADIOS2_ARCH_PATH", "/apps/spack/bell-20250305/apps/adios2/2.10.2-gcc-14.2.0-sun6hqf", ":")
prepend_path("BOOST_ARCH_PATH", "/apps/spack/bell-20250305/apps/boost/1.86.0-gcc-14.2.0-vhy3r3q", ":")
prepend_path("CGAL_ARCH_PATH", "/apps/spack/bell-20250305/apps/cgal/5.6-gcc-14.2.0-wogwnzy", ":")
prepend_path("FFTW_ARCH_PATH", "/apps/spack/bell-20250305/apps/fftw/3.3.10-gcc-8.5.0-5nxboyk", ":")
setenv("FOAM_API", "2312")
setenv("FOAM_APP", modroot.."/applications")
setenv("FOAM_APPBIN", modroot.."/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_ETC", modroot.."/etc")
setenv("FOAM_LIBBIN", modroot.."/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_MPI", "user-mpi")
setenv("FOAM_RUN", userhome.."/OpenFOAM/"..user.."-v2312/run")
setenv("FOAM_SITE_APPBIN", modroot.."/site/2312/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_SITE_LIBBIN", modroot.."/site/2312/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_SOLVERS", modroot.."/applications/solvers")
setenv("FOAM_SRC", modroot.."/src")
setenv("FOAM_TUTORIALS", modroot.."/tutorials")
setenv("FOAM_USER_APPBIN", userhome.."/OpenFOAM/"..user.."-v2312/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_USER_LIBBIN", userhome.."/OpenFOAM/"..user.."-v2312/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_UTILITIES", modroot.."/applications/utilities")
prepend_path("MPFR_ARCH_PATH", "/apps/spack/bell-20250305/apps/mpfr/4.2.1-gcc-8.5.0-xoj26oc", ":")
prepend_path("SCOTCH_ARCH_PATH", "/apps/spack/bell-20250305/apps/scotch/7.0.4-gcc-14.2.0-u3yffpq", ":")
setenv("SCOTCH_VERSION", "scotch-7.0.4")
setenv("WM_ARCH", "linux64")
setenv("WM_COMPILER", "Gcc")
setenv("WM_COMPILER_LIB_ARCH", "64")
setenv("WM_COMPILER_TYPE", "system")
setenv("WM_COMPILE_OPTION", "-spack")
setenv("WM_DIR", modroot.."/wmake")
setenv("WM_LABEL_OPTION", "Int32")
setenv("WM_LABEL_SIZE", "32")
setenv("WM_MPLIB", "USERMPI")
setenv("WM_OPTIONS", "linux64GccDPInt32-spack")
setenv("WM_PRECISION_OPTION", "DP")
setenv("WM_PROJECT", "OpenFOAM")
setenv("WM_PROJECT_DIR", modroot.."")
setenv("WM_PROJECT_USER_DIR", userhome.."/OpenFOAM/"..user.."-v2312")
setenv("WM_PROJECT_VERSION", "v2312")
setenv("WM_THIRD_PARTY_DIR", modroot.."/ThirdParty")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib/dummy", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/bell-20250305/apps/adios2/2.10.2-gcc-14.2.0-sun6hqf/lib64", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/bell-20250305/apps/mpfr/4.2.1-gcc-8.5.0-xoj26oc/lib", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/bell-20250305/apps/cgal/5.6-gcc-14.2.0-wogwnzy/lib64", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/bell-20250305/apps/boost/1.86.0-gcc-14.2.0-vhy3r3q/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib/user-mpi", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/site/2312/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("LD_LIBRARY_PATH", userhome.."/OpenFOAM/"..user.."-v2312/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("MANPATH", modroot.."/doc", ":")
prepend_path("PATH", modroot.."/wmake", ":")
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("PATH", modroot.."/platforms/linux64GccDPInt32-spack/bin", ":")
prepend_path("PATH", modroot.."/site/2312/platforms/linux64GccDPInt32-spack/bin", ":")
prepend_path("PATH", userhome.."/OpenFOAM/"..user.."-v2312/platforms/linux64GccDPInt32-spack/bin", ":")

prepend_path("PATH", "/apps/spack/bell-20250305/apps/adios2/2.10.2-gcc-14.2.0-sun6hqf/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/scotch/7.0.4-gcc-14.2.0-u3yffpq/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/parmgridgen/1.0-gcc-8.5.0-jzlfpx3/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/metis/5.1.0-gcc-14.2.0-wpofhqf/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/m4/1.4.19-gcc-14.2.0-svn3wvb/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/flex/2.6.4-gcc-14.2.0-xr4kb47/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/fftw/3.3.10-gcc-8.5.0-5nxboyk/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/cmake/3.30.5-gcc-8.5.0-r746jop/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/cgal/5.6-gcc-14.2.0-wogwnzy/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/openmpi/5.0.5-gcc-8.5.0-l2jmtbl/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/openssh/9.9p1-gcc-8.5.0-c2m44xj/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/tar/1.34-gcc-8.5.0-nsqdnuj/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/pigz/2.8-gcc-8.5.0-lwqcjlv/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/xz/5.4.6-gcc-8.5.0-jzfknv7/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/zstd/1.5.6-gcc-8.5.0-ylwnc6f/bin", ":")
prepend_path("PATH", "/apps/spack/bell-20250305/apps/bzip2/1.0.8-gcc-8.5.0-scsing2/bin", ":")
setenv("OPENFOAM_HOME", modroot.."")
setenv("RCAC_OPENFOAM_ROOT", modroot.."")
setenv("RCAC_OPENFOAM_VERSION", modroot.."")
