-- -*- lua -*-
-- Nextflow 26.04.2
-- Installed manually (non-Spack) to /apps/external/apps/nextflow/26.04.2
-- Generated by deploy-nextflow.sh on 2026-05-26 15:58 UTC

whatis([[Name : nextflow]])
whatis([[Version : 26.04.2]])
whatis([[Short description : Data-driven computational pipelines (https://nextflow.io)]])

help([[Nextflow 26.04.2
Requires Java 17+. Loads openjdk/17.0.5_8 automatically.
Documentation: https://nextflow.io/docs/stable/
]])

depends_on("openjdk/17.0.5_8")

prepend_path("PATH", "/apps/external/apps/nextflow/26.04.2/bin")
setenv("NEXTFLOW_HOME", "/apps/external/apps/nextflow/26.04.2")
setenv("RCAC_NEXTFLOW_ROOT", "/apps/external/apps/nextflow/26.04.2")
setenv("RCAC_NEXTFLOW_VERSION", "26.04.2")
