whatis([[Name: Intel® MPI Library]])
whatis([[Version : impi/2021.12]])
whatis([[Short description : Intel® MPI Library]])
whatis([[URL: https://www.intel.com/content/www/us/en/developer/tools/oneapi/mpi-library.html]])

family("mpi")

local modroot="/apps/anvil/external/apps/intel/oneapi/2024.1/mpi/2021.12"


setenv("I_MPI_ROOT",modroot)

prepend_path("CLASSPATH", modroot.."/share/java/mpi.jar", ":")
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("CPATH", modroot.."/include", ":")
prepend_path("MANPATH", modroot.."/share/man", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/", ":")
setenv("FI_PROVIDER_PATH", modroot.."/opt/mpi/libfabric/lib/prov:/usr/lib64/libfabric")
prepend_path("PATH", modroot.."/opt/mpi/libfabric/bin", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/opt/mpi/libfabric/lib", ":")
prepend_path("LIBRARY_PATH", modroot.."/opt/mpi/libfabric/lib", ":")

setenv("MPICC",modroot.."/bin/mpiicc")
setenv("MPICXX",modroot.."/bin/mpiicpc")
setenv("MPIF77",modroot.."/bin/mpiifort")
setenv("MPIF90",modroot.."/bin/mpiifort")
setenv("MPIFC",modroot.."/bin/mpiifort")
setenv("INTEL_MPI_HOME",modroot)
setenv("RCAC_INTEL_MPI_ROOT",modroot)
setenv("RCAC_INTEL_MPI_VERSION","2021.12")
setenv("CC","mpiicc")
setenv("CXX","mpiicpc")
setenv("FC","mpiifort")
setenv("F90","mpiifort")
setenv("F77","mpiifort")
setenv("I_MPI_CC","icc")
setenv("I_MPI_CXX","icpc")
setenv("I_MPI_FC","ifort")
setenv("I_MPI_F77","ifort")
setenv("I_MPI_F90","ifort")
setenv("I_MPI_FABRICS","shm:ofi")
setenv("FI_PROVIDER","verbs")
