whatis([[Name : intel-parallel-studio]])
whatis([[Version : cluster.2020.4]])
whatis([[Short description : Intel Parallel Studio.]])

help([[Intel Parallel Studio.]])



local modroot="/apps/external/intel/apps/intel-parallel-studio/cluster.2019.5-intel-19.0.5-4brgqlf"
local modroot="/apps/external/intel/"
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("MANPATH", modroot.."/man", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("CPATH", modroot.."/include", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/", ":")
setenv("ADVISOR_2020_DIR", modroot.."/advisor_2020.3.0.607294")
prepend_path("CLASSPATH", modroot.."/intelpython3/lib/mpi.jar:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/mpi.jar:"..modroot.."/compilers_and_libraries_2020.4.304/linux/daal/lib/daal.jar", ":")
setenv("CLCK_ROOT", modroot.."/clck/2019.10")
setenv("CONDA_DEFAULT_ENV", "root")
prepend_path("CONDA_PATH_BACKUP", modroot.."/advisor_2020.3.0.607294/bin64:"..modroot.."/vtune_amplifier_2020.3.0.612611/bin64:"..modroot.."/inspector_2020.3.0.604771/bin64:"..modroot.."/itac/2020.3.036/intel64/bin:"..modroot.."/itac/2020.3.036/intel64/bin:"..modroot.."/clck/2019.10/bin/intel64:"..modroot.."/compilers_and_libraries_2020.4.304/linux/bin/intel64:"..modroot.."/compilers_and_libraries_2020.4.304/linux/bin:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/bin:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin:"..modroot.."/debugger_2020/gdb/intel64/bin:/apps/spack/bell/framework/spack/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/site/rcac/sbin:/usr/site/rcac/bin:/opt/hpss/bin:/opt/hsi/bin:/opt/ibutils/bin:/opt/thinlinc/bin", ":")
setenv("CONDA_PREFIX", modroot.."/intelpython3")
setenv("CONDA_PS1_BACKUP", "")
prepend_path("CPATH", modroot.."/compilers_and_libraries_2020.4.304/linux/ipp/include:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mkl/include:"..modroot.."/compilers_and_libraries_2020.4.304/linux/pstl/include:"..modroot.."/compilers_and_libraries_2020.4.304/linux/tbb/include:"..modroot.."/compilers_and_libraries_2020.4.304/linux/tbb/include:"..modroot.."/compilers_and_libraries_2020.4.304/linux/daal/include", ":")
prepend_path("CPLUS_INCLUDE_PATH", modroot.."/clck/2019.10/include", ":")
setenv("DAALROOT", modroot.."/compilers_and_libraries_2020.4.304/linux/daal")
prepend_path("FI_PROVIDER_PATH", modroot.."/intelpython3/lib/libfabric/prov", ":")
prepend_path("INFOPATH", modroot.."/documentation_2020/en/debugger/gdb-ia/info/", ":")
setenv("INSPECTOR_2020_DIR", modroot.."/inspector_2020.3.0.604771")
prepend_path("INTEL_LICENSE_FILE", modroot.."/licenses:/opt/intel/licenses:"..modroot.."/intel/licenses:"..modroot.."/compilers_and_libraries_2020.4.304/linux/licenses:/opt/intel/licenses:/home/rcactest/intel/licenses:"..modroot.."/clck/2019.10/licenses:/opt/intel/licenses:/home/rcactest/intel/licenses:/Users/Shared/Library/Application Support/Intel/Licenses", ":")
setenv("INTEL_PYTHONHOME", modroot.."/debugger_2020/python/intel64/")
setenv("IPPROOT", modroot.."/compilers_and_libraries_2020.4.304/linux/ipp")
setenv("I_MPI_ROOT", modroot.."/compilers_and_libraries_2020.4.304/linux/mpi")
prepend_path("LD_LIBRARY_PATH", modroot.."/intelpython3/lib/libfabric:"..modroot.."/intelpython3/lib:"..modroot.."/itac/2020.3.036/intel64/slib:"..modroot.."/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/lib:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib/release:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/lib:"..modroot.."/compilers_and_libraries_2020.4.304/linux/ipp/lib/intel64:"..modroot.."/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin:"..modroot.."/compilers_and_libraries_2020.4.304/linux/tbb/lib/intel64/gcc4.8:"..modroot.."/compilers_and_libraries_2020.4.304/linux/tbb/lib/intel64_lin/gcc4.8:"..modroot.."/debugger_2020/libipt/intel64/lib:"..modroot.."/compilers_and_libraries_2020.4.304/linux/daal/lib/intel64_lin", ":")
prepend_path("LIBRARY_PATH", modroot.."/intelpython3/lib/libfabric:"..modroot.."/clck/2019.10/lib/intel64:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/lib:"..modroot.."/compilers_and_libraries_2020.4.304/linux/ipp/lib/intel64:"..modroot.."/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin:"..modroot.."/compilers_and_libraries_2020.4.304/linux/tbb/lib/intel64/gcc4.8:"..modroot.."/compilers_and_libraries_2020.4.304/linux/tbb/lib/intel64/gcc4.8:"..modroot.."/compilers_and_libraries_2020.4.304/linux/daal/lib/intel64_lin:", ":")
setenv("MKLROOT", modroot.."/compilers_and_libraries_2020.4.304/linux/mkl")
prepend_path("NLSPATH", modroot.."/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64/locale/%l_%t/%N:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64_lin/locale/%l_%t/%N:"..modroot.."/debugger_2020/gdb/intel64/share/locale/%l_%t/%N", ":")
prepend_path("PKG_CONFIG_PATH", modroot.."/advisor_2020.3.0.607294/include/pkgconfig/lib64:"..modroot.."/inspector_2020.3.0.604771/include/pkgconfig/lib64:"..modroot.."/compilers_and_libraries_2020.4.304/linux/mkl/bin/pkgconfig", ":")
setenv("PSTLROOT", modroot.."/compilers_and_libraries_2020.4.304/linux/pstl")
setenv("PSXE_2020", "1")
prepend_path("PYTHONPATH", modroot.."/advisor_2020.3.0.607294/pythonapi", ":")
setenv("TBBROOT", modroot.."/compilers_and_libraries_2020.4.304/linux/tbb")
setenv("VT_ADD_LIBS", "-ldwarf -lelf -lvtunwind -lm -lpthread")
setenv("VT_ARCH", "intel64")
setenv("VT_LIB_DIR", modroot.."/itac/2020.3.036/intel64/lib")
setenv("VT_MPI", "impi4")
setenv("VT_ROOT", modroot.."/itac/2020.3.036")
setenv("VT_SLIB_DIR", modroot.."/itac/2020.3.036/intel64/slib")
prepend_path("MANPATH", modroot.."/documentation_2020/en/debugger/gdb-ia/man/", ":")
prepend_path("MANPATH", modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/man", ":")
prepend_path("MANPATH", modroot.."/man/common", ":")
prepend_path("MANPATH", modroot.."/clck/2019.10/man", ":")
prepend_path("MANPATH", modroot.."/itac/2020.3.036/man", ":")
prepend_path("MANPATH", modroot.."/intelpython3/share/man", ":")
append_path("PATH", modroot.."/parallel_studio_xe_2020.4.912/bin", ":")
prepend_path("PATH", modroot.."/debugger_2020/gdb/intel64/bin", ":")
prepend_path("PATH", modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/bin", ":")
prepend_path("PATH", modroot.."/compilers_and_libraries_2020.4.304/linux/mpi/intel64/libfabric/bin", ":")
prepend_path("PATH", modroot.."/compilers_and_libraries_2020.4.304/linux/bin", ":")
prepend_path("PATH", modroot.."/compilers_and_libraries_2020.4.304/linux/bin/intel64", ":")
prepend_path("PATH", modroot.."/clck/2019.10/bin/intel64", ":")
prepend_path("PATH", modroot.."/itac/2020.3.036/intel64/bin", ":")
prepend_path("PATH", modroot.."/itac/2020.3.036/intel64/bin", ":")
prepend_path("PATH", modroot.."/inspector_2020.3.0.604771/bin64", ":")
prepend_path("PATH", modroot.."/advisor_2020.3.0.607294/bin64", ":")
prepend_path("PATH", modroot.."/intelpython3/bin", ":")
prepend_path("PATH", modroot.."/intelpython3/bin/libfabric", ":")
setenv("INTEL_PARALLEL_STUDIO_HOME", modroot)
setenv("RCAC_INTEL_PARALLEL_STUDIO_ROOT", modroot)
setenv("RCAC_INTEL_PARALLEL_STUDIO_VERSION", "cluster.2020.4")
setenv("CC", "icc")
setenv("CXX", "icpc")
setenv("FC", "ifort")
setenv("F90", "ifort")
setenv("F77", "ifort")
setenv("MKL_DEBUG_CPU_TYPE", "5")
setenv("MKL_CBWR", "AUTO")


-- Services provided by the package
family("compiler")
