#!/usr/bin/env python3
"""Import the HUBzero documentation into RCAC-Docs, and check the result.

Usage (from the repo root):

    HUBZERO_CMS=/path/to/hubzero-cms .venv/bin/python tools/hubzero/import_docs.py import
    HUBZERO_CMS=/path/to/hubzero-cms .venv/bin/python tools/hubzero/import_docs.py check [--final]

`import` regenerates docs/hubzero/**, docs/assets/images/hubzero/**, and the
HUBzero region of the mkdocs.yml nav from the hubzero-cms repository at the
commit pinned in tools/hubzero/import.yml. It reads every file with `git`
at that commit, never from the clone's working tree, so the output depends
only on the commit and this script.

`check` is the acceptance gate (spec/hubzero-docs/GOAL.md R2-R8). It
re-imports in memory and compares byte-for-byte with what is committed, then
checks the pages themselves and, after `mkdocs build`, the built site/hubzero/.

The rules mirror hubzero-cms gh-pages/build_site.py (parse_meta, order_key_for,
slug_for, slugify, expand_includes, make_link_resolver, and the heading ids),
so the port shows what hubzero.github.io shows. See tools/hubzero/README.md.
"""

from __future__ import annotations

import argparse
import html
import os
import re
import shutil
import subprocess
import sys
import unicodedata
from dataclasses import dataclass, field
from html.parser import HTMLParser
from pathlib import Path, PurePosixPath
from urllib.parse import unquote

import markdown
import yaml
from markdown.extensions.toc import unique as pm_unique

ROOT = Path(__file__).resolve().parents[2]
CONFIG = ROOT / "tools" / "hubzero" / "import.yml"
DOCS = ROOT / "docs"
SITE = ROOT / "site"
MKDOCS_YML = ROOT / "mkdocs.yml"
PAGES_DIR = "hubzero"                       # under docs/
ASSETS_DIR = "assets/images/hubzero"        # under docs/
NAV_BEGIN = "  # >>> hubzero nav (generated by tools/hubzero/import_docs.py; do not edit)"
NAV_END = "  # <<< hubzero nav"
NAV_ANCHOR = "  - Contact us: contact.md"
NAV_TITLE = "HUBzero"
ABOUT_GROUP = "About these docs"

# --- upstream constants (gh-pages/build_site.py) ---------------------------------
SKIP_DOC_DIRS = {"_import", "_tools", "plan"}
COPIED_SUFFIXES = {".png", ".jpg", ".jpeg", ".gif", ".svg", ".webp", ".pdf", ".zip", ".gz", ".csv"}
LANDING_NAMES = ("readme.md", "index.md")
ORDER_PREFIX_RE = re.compile(r"^(\d+)[-_.]\s*")
META_COMMENT_RE = re.compile(r"^\s*<!--(.*?)-->", re.S)
INCLUDE_RE = re.compile(r"<!--\s*include:\s*([^>]+?)\s*-->")
INCLUDE_LANGS = {
    ".php": "php", ".py": "python", ".sh": "bash", ".json": "json", ".xml": "xml",
    ".ini": "ini", ".yml": "yaml", ".yaml": "yaml", ".md": "markdown", ".js": "javascript",
    ".css": "css", ".less": "less", ".html": "html", ".sql": "sql", ".conf": "apache",
}
HTTP_METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS")


class ImportError_(Exception):
    """A fatal import problem (bad config, missing commit, output collision)."""


# =================================================================== upstream rules


def slugify(text: str) -> str:
    """build_site.slugify: the upstream anchor and URL slug."""
    normalized = unicodedata.normalize("NFKD", text)
    ascii_text = normalized.encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-zA-Z0-9]+", "-", ascii_text.lower()).strip("-")
    return slug or "section"


def parse_meta(text: str) -> tuple[dict[str, str], str, str]:
    """build_site.parse_meta, also returning the header comment itself."""
    match = META_COMMENT_RE.match(text)
    if not match:
        return {}, text, ""
    meta: dict[str, str] = {}
    for line in match.group(1).strip().splitlines():
        line = line.strip().rstrip(";")
        if not line:
            continue
        key, sep, value = line.partition(":")
        if not sep or not re.fullmatch(r"[a-z][a-z0-9-]*", key.strip()):
            return {}, text, ""
        meta[key.strip()] = value.strip()
    return meta, text[match.end():], match.group(0)


def order_key_for(name: str, meta: dict[str, str]) -> tuple[int, str]:
    if meta.get("order", "").isdigit():
        return int(meta["order"]), name.lower()
    match = ORDER_PREFIX_RE.match(name)
    if match:
        return int(match.group(1)), name.lower()
    return 10_000, name.lower()


def slug_for(name: str) -> str:
    stem = name[:-3] if name.lower().endswith(".md") else name
    return slugify(ORDER_PREFIX_RE.sub("", stem))


def title_from_name(name: str) -> str:
    stem = ORDER_PREFIX_RE.sub("", name[:-3] if name.lower().endswith(".md") else name)
    return stem.replace("-", " ").replace("_", " ").strip().capitalize()


def first_heading(text: str) -> str | None:
    for line in text.splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return None


def plain_text(title: str) -> str:
    """A heading as plain text, for nav labels."""
    text = re.sub(r"!?\[([^\]]*)\]\([^)]*\)", r"\1", title)
    text = text.replace("`", "")
    text = re.sub(r"(\*\*|__)(.+?)\1", r"\2", text)
    text = re.sub(r"(?<!\w)[*_](.+?)[*_](?!\w)", r"\1", text)
    return re.sub(r"<[^>]+>", "", text).strip()


# =================================================================== source access


class Source:
    """Read-only view of the hubzero-cms repository at one commit."""

    def __init__(self, repo: Path, commit: str) -> None:
        self.repo = repo
        self.commit = commit
        if not (repo / ".git").exists() and not (repo / "HEAD").exists():
            raise ImportError_(f"$HUBZERO_CMS={repo} is not a git clone of hubzero-cms")
        probe = subprocess.run(
            ["git", "-C", str(repo), "cat-file", "-e", f"{commit}^{{commit}}"],
            capture_output=True,
        )
        if probe.returncode != 0:
            raise ImportError_(
                f"commit {commit} is not in {repo}. Fetch it with:\n"
                f"  git -C {repo} fetch --depth=1 origin {commit}"
            )
        listing = subprocess.run(
            ["git", "-C", str(repo), "ls-tree", "-r", "-z", commit],
            capture_output=True, check=True,
        ).stdout.decode("utf-8")
        self.blobs: dict[str, str] = {}
        for entry in filter(None, listing.split("\0")):
            info, path = entry.split("\t", 1)
            _mode, kind, oid = info.split()
            if kind == "blob":
                self.blobs[path] = oid
        self.dirs: set[str] = set()
        for path in self.blobs:
            parts = PurePosixPath(path).parts[:-1]
            for i in range(1, len(parts) + 1):
                self.dirs.add("/".join(parts[:i]))
        self._cache: dict[str, bytes] = {}

    def is_file(self, path: str) -> bool:
        return path in self.blobs

    def is_dir(self, path: str) -> bool:
        return path.rstrip("/") in self.dirs

    def read_bytes(self, path: str) -> bytes:
        if path not in self._cache:
            self._cache[path] = subprocess.run(
                ["git", "-C", str(self.repo), "cat-file", "blob", self.blobs[path]],
                capture_output=True, check=True,
            ).stdout
        return self._cache[path]

    def read_text(self, path: str) -> str:
        return self.read_bytes(path).decode("utf-8").replace("\r\n", "\n")

    def children(self, directory: str) -> list[tuple[str, bool]]:
        """(name, is_dir) for the direct children of a directory, sorted by name."""
        prefix = directory.rstrip("/") + "/"
        names: dict[str, bool] = {}
        for path in self.blobs:
            if path.startswith(prefix):
                rest = path[len(prefix):]
                head, sep, _ = rest.partition("/")
                names[head] = names.get(head, False) or bool(sep)
        return sorted(names.items())


# =================================================================== page model


@dataclass
class Page:
    source: str | None          # repo path, e.g. docs/tools/01-intro.md (None: synthetic section)
    output: str | None          # docs-relative path, e.g. hubzero/tools/intro.md
    title: str
    book: str | None            # book slug; None for root pages
    meta: dict[str, str] = field(default_factory=dict)
    body: str = ""
    header: str = ""
    order: tuple[int, str] = (0, "")
    children: list["Page"] = field(default_factory=list)
    is_section: bool = False
    landing: bool = False

    def walk(self) -> list["Page"]:
        pages = [self]
        for child in self.children:
            pages.extend(child.walk())
        return pages


def read_page(src: Source, path: str) -> tuple[dict[str, str], str, str, str]:
    meta, body, header = parse_meta(src.read_text(path))
    title = meta.get("title") or first_heading(body) or title_from_name(PurePosixPath(path).name)
    return meta, body, header, title


def output_for(parts: list[str], leaf: str | None, collisions: dict[str, str], source: str) -> str:
    if source in collisions:
        return collisions[source]
    base = "/".join([PAGES_DIR, *parts])
    return f"{base}/index.md" if leaf is None else f"{base}/{leaf}.md"


def load_section(src: Source, directory: str, parts: list[str], book: str,
                 collisions: dict[str, str]) -> Page:
    """build_site.load_section, producing RCAC-Docs output paths."""
    names = dict(src.children(directory))
    landing_name = next((n for n in ("README.md", "index.md") if n in names and not names[n]), None)
    dir_name = PurePosixPath(directory).name
    if landing_name:
        path = f"{directory}/{landing_name}"
        meta, body, header, title = read_page(src, path)
        section = Page(source=path, output=output_for(parts, None, collisions, path), title=title,
                       book=book, meta=meta, body=body, header=header, is_section=True)
    else:
        section = Page(source=None, output=None, title=title_from_name(dir_name), book=book,
                       is_section=True)
    section.order = order_key_for(dir_name, section.meta)
    entries: list[Page] = []
    for name, is_dir in names.items():
        if name.startswith((".", "_")) or name == "media":
            continue
        child = f"{directory}/{name}"
        if is_dir:
            if any(p.startswith(child + "/") and p.lower().endswith(".md") for p in src.blobs):
                entries.append(load_section(src, child, parts + [slug_for(name)], book, collisions))
        elif name.lower().endswith(".md") and name.lower() not in LANDING_NAMES:
            meta, body, header, title = read_page(src, child)
            leaf = Page(source=child, output=output_for(parts, slug_for(name), collisions, child),
                        title=title, book=book, meta=meta, body=body, header=header)
            leaf.order = order_key_for(name, meta)
            entries.append(leaf)
    entries.sort(key=lambda p: p.order)
    section.children = entries
    return section


@dataclass
class Model:
    config: dict
    src: Source
    books: list[Page]           # every published book, in site.json order
    roots: list[Page]           # root pages (README, STYLE, LICENSE)
    enabled: list[str]

    def pages(self) -> list[Page]:
        """Every real page that is imported now: root pages, then enabled books."""
        out = list(self.roots)
        for book in self.books:
            if book.book in self.enabled:
                out.extend(p for p in book.walk() if p.source)
        return out

    def all_pages(self) -> list[Page]:
        return list(self.roots) + [p for b in self.books for p in b.walk() if p.source]


def build_model(config: dict, src: Source) -> Model:
    collisions = dict(config.get("collisions") or {})
    enabled = list(config.get("books") or [])
    known = [b["slug"] for b in config["all_books"]]
    for slug in enabled:
        if slug not in known:
            raise ImportError_(f"import.yml: unknown book {slug!r}")
    books = []
    for entry in config["all_books"]:
        root = load_section(src, entry["dir"], [entry["slug"]], entry["slug"], collisions)
        root.title = entry["title"]     # upstream: book.root.title = site.json title
        books.append(root)
    roots = []
    for entry in config["root_pages"]:
        meta, body, header, _title = read_page(src, entry["source"])
        roots.append(Page(source=entry["source"], output=entry["output"],
                          title=first_heading(body) or entry["title"], book=None, meta=meta,
                          body=body, header=header, landing=bool(entry.get("landing"))))
    model = Model(config=config, src=src, books=books, roots=roots, enabled=enabled)
    seen: dict[str, str] = {}
    for page in model.all_pages():
        if page.output in seen:
            raise ImportError_(f"two pages map to {page.output}: {seen[page.output]} and "
                               f"{page.source}; add one to `collisions` in import.yml")
        seen[page.output] = page.source
    return model


# =================================================================== markdown scanning

FENCE_OPEN_RE = re.compile(r"^(?P<ind>[ \t]*)(?P<fence>`{3,}|~{3,})(?P<info>.*)$")
ATX_RE = re.compile(r"^ {0,3}(#{1,6})(?:[ \t]+(.*?))?(?:[ \t]+#+)?[ \t]*$")
LIST_RE = re.compile(r"^(?P<ind>[ \t]*)(?P<mark>[-*+]|\d{1,9}[.)])(?P<sp>[ \t]+|$)(?P<rest>.*)$")
HR_RE = re.compile(r"^ {0,3}([-*_])(?:[ \t]*\1){2,}[ \t]*$")
TABLE_ROW_RE = re.compile(r"^ {0,3}\|")
CODE_SPAN_RE = re.compile(r"(`+)(?!`)(.+?)(?<!`)\1(?!`)")


def indent_of(line: str) -> int:
    lead = line[: len(line) - len(line.lstrip(" \t"))]
    return len(lead.expandtabs(4))


def reindent(line: str, width: int) -> str:
    return " " * max(width, 0) + line.lstrip(" \t")


def line_kinds(lines: list[str]) -> list[str]:
    """Classify each line: 'fence' (inside or delimiting a fenced block), 'code'
    (indented code block), 'html' (raw HTML block), 'blank', or 'text'."""
    kinds: list[str] = []
    fence: tuple[str, int, int] | None = None
    prev = "blank"
    html = False
    for line in lines:
        if fence is not None:
            kinds.append("fence")
            m = FENCE_OPEN_RE.match(line)
            if (m and m.group("fence")[0] == fence[0] and len(m.group("fence")) >= fence[1]
                    and not m.group("info").strip()):
                fence = None
            continue
        if not line.strip():
            kinds.append("blank")
            prev, html = "blank", False
            continue
        m = FENCE_OPEN_RE.match(line)
        if m and not (m.group("fence")[0] == "`" and "`" in m.group("info")):
            fence = (m.group("fence")[0], len(m.group("fence")), indent_of(line))
            kinds.append("fence")
            prev = "fence"
            continue
        if html:
            kinds.append("html")
            continue
        if prev in ("blank", "code") and indent_of(line) >= 4 and (not kinds or _top_level(lines, len(kinds))):
            kinds.append("code")
            prev = "code"
            continue
        if indent_of(line) <= 3 and re.match(r"^\s*<(?!!--\s*include)[A-Za-z!/]", line):
            html = True
            kinds.append("html")
            prev = "html"
            continue
        kinds.append("text")
        prev = "text"
    return kinds


def _top_level(lines: list[str], index: int) -> bool:
    """True if the nearest preceding non-blank text is not inside a list item,
    so a 4-space-indented line there is an indented code block."""
    for line in reversed(lines[:index]):
        if not line.strip():
            continue
        if LIST_RE.match(line) and not HR_RE.match(line):
            return False
        if indent_of(line) == 0:
            return True
    return True


def mask_code_spans(line: str) -> str:
    """Blank out inline code so links inside it are not rewritten."""
    return CODE_SPAN_RE.sub(lambda m: "\0" * len(m.group(0)), line)


# =================================================================== transforms


def expand_includes(text: str, src: Source, warn) -> str:
    """build_site.expand_includes, reading from the pinned commit.

    Unlike upstream, a directive inside a fenced or indented code block is left
    alone: STYLE.md shows the directive itself in a ```markdown fence, and
    expanding it there nests fences and breaks the rest of the page."""
    lines = text.split("\n")
    kinds = line_kinds(lines)
    return "\n".join(
        line if kind in ("fence", "code") else _expand_line(line, src, warn)
        for line, kind in zip(lines, kinds)
    )


def _expand_line(text: str, src: Source, warn) -> str:

    def replace(match: re.Match[str]) -> str:
        spec = match.group(1).strip()
        rel, _, span = spec.partition(":")
        if not src.is_file(rel):
            warn(f"include of missing file {rel!r}")
            return match.group(0)
        lines = src.read_text(rel).splitlines()
        if span:
            start, _, end = span.partition("-")
            lines = lines[max(int(start) - 1, 0): int(end or len(lines))]
        # A directive indented into a list item keeps the whole block there.
        ind = text[: len(text) - len(text.lstrip(" \t"))] if text.lstrip().startswith("<!--") else ""
        body = "\n".join(ind + ln if ln.strip() else "" for ln in lines).rstrip("\n")
        lang = INCLUDE_LANGS.get(PurePosixPath(rel).suffix, "")
        return f"```{lang}\n{body}\n{ind}```"

    return INCLUDE_RE.sub(replace, text)


LINK_DEST_RE = re.compile(
    r"(?P<pre>\]\(\s*)(?P<dest><[^<>\n]*>|[^\s()<>]*(?:\([^\s()]*\)[^\s()<>]*)*)"
    r"(?P<post>(?:\s+(?:\"[^\"]*\"|'[^']*'|\([^)]*\)))?\s*\))"
)
REF_DEF_RE = re.compile(r"^(?P<pre> {0,3}\[[^\]]+\]:[ \t]*)(?P<dest><[^>]*>|\S+)(?P<post>.*)$")
HTML_ATTR_RE = re.compile(r"""(?P<attr>\b(?:href|src|srcset)\s*=\s*)(?P<q>["'])(?P<url>[^"']*)(?P=q)""")


def pages_path(output: str) -> str:
    """A page's URL path under /hubzero/, as hubzero.github.io lays it out ('' is the landing)."""
    rel = output[len(PAGES_DIR) + 1:]
    if rel == "index.md":
        return ""
    if rel.endswith("/index.md"):
        return rel[: -len("index.md")]
    return rel[: -len(".md")] + "/"


BARE_URL_RE = re.compile(r"https?://[^\s<>()\[\]\"'`]+")


class Resolver:
    """build_site.make_link_resolver, rewritten for RCAC-Docs (PLAN §2, transform 3-4)."""

    def __init__(self, model: Model, page: Page, warn) -> None:
        self.model = model
        self.page = page
        self.warn = warn
        self.src = model.src
        commit = model.config["commit"]
        base = model.config["repo"].rstrip("/")
        self.blob_base = f"{base}/blob/{commit}"
        self.tree_base = f"{base}/tree/{commit}"
        self.by_source = {p.source: p for p in model.all_pages()}
        self.assets: set[str] = set()
        self.fallbacks = 0
        # GOAL R12: references to the GitHub Pages site point here instead.
        pages_url = model.config.get("pages_url", "").rstrip("/")
        self.pages_re = (re.compile(r"https?://" + re.escape(pages_url.split("://", 1)[-1])
                                    + r"(?=/|#|$)", re.I) if pages_url else None)
        self.by_pages_path = {pages_path(p.output): p for p in model.all_pages() if p.output}
        self.pages_rewrites = 0

    def _pages_target(self, href: str) -> tuple["Page", str] | None:
        rest = self.pages_re.sub("", href, count=1).lstrip("/")
        path, _sep, fragment = rest.partition("#")
        target = (self.model.config.get("pages_targets") or {}).get(path)
        if target:
            source, _s, default_fragment = target.partition("#")
            page = self.by_source.get(source)
            fragment = fragment or default_fragment
        else:
            page = self.by_pages_path.get(path if not path or path.endswith("/") else path + "/")
        if page is None:
            self.warn(f"GitHub Pages link with no page here {href!r}")
            return None
        self.pages_rewrites += 1
        return page, fragment

    def pages_link(self, href: str) -> str:
        """A GitHub Pages link → a relative link to the same page here."""
        hit = self._pages_target(href)
        if hit is None:
            return href
        dest, fragment = hit
        if dest is self.page and fragment:
            return f"#{fragment}"
        if dest.book is None or dest.book in self.model.enabled:
            out = os.path.relpath(dest.output, os.path.dirname(self.page.output)).replace(os.sep, "/")
        else:
            self.fallbacks += 1
            out = f"{self.blob_base}/{dest.source}"
        return out + (f"#{fragment}" if fragment else "")

    def pages_absolute(self, url: str) -> str:
        """A bare GitHub Pages URL in prose → the same page's absolute URL here."""
        hit = self._pages_target(url)
        if hit is None:
            return url
        dest, fragment = hit
        base = self.model.config["site_url"].rstrip("/")
        return f"{base}/{pages_path(dest.output)}" + (f"#{fragment}" if fragment else "")

    def _prefix_insensitive(self, candidate: str) -> str | None:
        def norm(part: str) -> str:
            return "readme.md" if part.lower() == "readme.md" else slug_for(part)
        want = [norm(p) for p in PurePosixPath(candidate).parts]
        for known in sorted(self.by_source):
            parts = PurePosixPath(known).parts
            if len(parts) == len(want) and all(norm(p) == w for p, w in zip(parts, want)):
                return known
        return None

    def __call__(self, href: str) -> str:
        if not href or href.startswith(("#", "//")):
            return href
        if self.pages_re and self.pages_re.match(href):
            return self.pages_link(href)
        if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", href):
            return href
        path_part, sep, fragment = href.partition("#")
        if not path_part:
            return href
        source_dir = PurePosixPath(self.page.source).parent
        target = os.path.normpath(str(source_dir / unquote(path_part))).replace(os.sep, "/")
        if target.startswith(".."):
            self.warn(f"link outside the repository {href!r}")
            return href
        candidates = [target]
        if not target.lower().endswith(".md"):
            candidates += [f"{target.rstrip('/')}/README.md", f"{target.rstrip('/')}/index.md"]
        for candidate in candidates:
            found = candidate if candidate in self.by_source else self._prefix_insensitive(candidate)
            if found is None:
                continue
            dest = self.by_source[found]
            if dest.book is None or dest.book in self.model.enabled:
                rel = os.path.relpath(dest.output, os.path.dirname(self.page.output))
                return rel.replace(os.sep, "/") + sep + fragment
            self.fallbacks += 1
            return f"{self.blob_base}/{dest.source}" + sep + fragment
        if (target.startswith("docs/") and self.src.is_file(target)
                and PurePosixPath(target).suffix.lower() in COPIED_SUFFIXES):
            self.assets.add(target)
            return f"/{ASSETS_DIR}/{target[len('docs/'):]}" + sep + fragment
        if self.src.is_file(target):
            return f"{self.blob_base}/{target}" + sep + fragment
        if self.src.is_dir(target):
            return f"{self.tree_base}/{target.rstrip('/')}" + sep + fragment
        # A source file missing at the commit (an upstream defect): link its
        # nearest existing directory, so the link still lands somewhere real.
        parent = PurePosixPath(target).parent
        while str(parent) not in ("", ".") and not self.src.is_dir(str(parent)):
            parent = parent.parent
        if str(parent) not in ("", "."):
            self.warn(f"link to missing file {path_part!r}; linked its directory {str(parent)!r}")
            return f"{self.tree_base}/{parent}"
        self.warn(f"link to missing file {path_part!r}")
        return href

    def srcset(self, value: str) -> str:
        out = []
        for candidate in value.split(","):
            stripped = candidate.strip()
            if stripped:
                url, _, descriptor = stripped.partition(" ")
                out.append(f"{self(url)} {descriptor.strip()}".strip())
        return ", ".join(out)


def rewrite_links(lines: list[str], kinds: list[str], resolve: Resolver) -> list[str]:
    out = []
    for line, kind in zip(lines, kinds):
        if kind in ("fence", "code", "blank"):
            out.append(line)
            continue
        masked = mask_code_spans(line)
        pieces: list[tuple[int, int, str]] = []

        def take(match: re.Match[str], group: str, new: str) -> None:
            pieces.append((match.start(group), match.end(group), new))

        if kind == "text":
            ref = REF_DEF_RE.match(masked)
            if ref:
                dest = ref.group("dest")
                inner = dest[1:-1] if dest.startswith("<") else dest
                new = resolve(inner)
                take(ref, "dest", f"<{new}>" if dest.startswith("<") else new)
            else:
                for m in LINK_DEST_RE.finditer(masked):
                    dest = m.group("dest")
                    inner = dest[1:-1] if dest.startswith("<") else dest
                    new = resolve(inner)
                    if new != inner:
                        take(m, "dest", f"<{new}>" if dest.startswith("<") else new)
        for m in HTML_ATTR_RE.finditer(masked):
            url = m.group("url")
            new = resolve.srcset(url) if "srcset" in m.group("attr").lower() else resolve(url)
            if new != url:
                take(m, "url", new)
        for start, end, new in sorted(pieces, reverse=True):
            line = line[:start] + new + line[end:]
        out.append(line)
    return out


def rewrite_pages_text(lines: list[str], kinds: list[str], resolve: Resolver) -> list[str]:
    """Bare GitHub Pages URLs left in prose after rewrite_links → this site (GOAL R12)."""
    if resolve.pages_re is None:
        return lines
    out = []
    for line, kind in zip(lines, kinds):
        if kind in ("fence", "code", "blank"):
            out.append(line)
            continue
        masked = mask_code_spans(line)
        pieces = []
        for m in BARE_URL_RE.finditer(masked):
            url = m.group(0).rstrip(".,;:!?")
            if resolve.pages_re.match(url):
                pieces.append((m.start(), m.start() + len(url), resolve.pages_absolute(url)))
        for start, end, new in sorted(pieces, reverse=True):
            line = line[:start] + new + line[end:]
        out.append(line)
    return out


_PM = markdown.Markdown(extensions=["toc", "attr_list"])


def pm_base_id(heading_line: str) -> str:
    """The id Python-Markdown's toc gives this heading line on its own."""
    _PM.reset()
    html = _PM.convert(heading_line)
    m = re.search(r'<h[1-6][^>]*\bid="([^"]*)"', html)
    return m.group(1) if m else ""


def upstream_text(raw: str) -> str:
    """The heading text upstream slugifies: markdown-it inline content, tags and backticks removed."""
    return re.sub(r"<[^>]+>", "", raw).strip().replace("`", "")


def add_heading_ids(lines: list[str], kinds: list[str]) -> tuple[list[str], int]:
    """Append `{ #<upstream id> }` where Python-Markdown's id would differ (PLAN §2, transform 5)."""
    heads = []   # (index, level, upstream id, python-markdown base id, ends in brace)
    counts: dict[str, int] = {}
    for i, (line, kind) in enumerate(zip(lines, kinds)):
        if kind != "text":
            continue
        m = ATX_RE.match(line)
        if not m or not (m.group(2) or "").strip():
            continue
        text = upstream_text(m.group(2))
        if not text:
            continue
        base = slugify(text)
        n = counts.get(base, 0)
        counts[base] = n + 1
        up = base if n == 0 else f"{base}-{n + 1}"
        heads.append((i, len(m.group(1)), up, pm_base_id(line.strip()), line.rstrip().endswith("}")))
    explicit = {i for i, level, _up, _pm, brace in heads if brace and level > 1}
    while True:
        used = {up for i, _l, up, _p, _b in heads if i in explicit}
        changed = False
        for i, level, up, pm, _brace in heads:
            if i in explicit:
                continue
            got = pm_unique(pm, used) if pm else ""
            if got != up and level > 1:
                explicit.add(i)
                changed = True
                break
            used.add(got)
        if not changed:
            break
    out = list(lines)
    for i, _level, up, _pm, _brace in heads:
        if i in explicit:
            out[i] = out[i].rstrip() + f" {{ #{up} }}"
    return out, len(explicit)


CALLOUT_RE = re.compile(
    r"^(?P<ind>[ \t]*)>[ \t]?\*\*(?P<label>note|tip|warning|important|caution):?\*\*:?[ \t]*(?P<rest>.*)$",
    re.I,
)
QUOTE_RE = re.compile(r"^(?P<ind>[ \t]*)>[ \t]?(?P<rest>.*)$")


def starts_block(line: str) -> bool:
    """True if the line opens a block (list item, heading, fence, rule), so it
    ends a blockquote instead of continuing it lazily, as in CommonMark."""
    return bool(LIST_RE.match(line) or ATX_RE.match(line) or HR_RE.match(line)
                or FENCE_OPEN_RE.match(line))


def convert_callouts(lines: list[str], kinds: list[str]) -> tuple[list[str], int]:
    """`> **Note:** …` blockquotes → Material admonitions (`!!! note`).

    Upstream's _apply_admonitions turns a blockquote whose first bold run is
    one of Note/Tip/Warning/Important/Caution into a styled callout (STYLE.md,
    "Notes and warnings"). Material has the same five types (important and
    caution are aliases of tip and warning), so the label becomes the type and
    its default title, and leaves the body. Any other blockquote is untouched."""
    out: list[str] = []
    count = 0
    i = 0
    while i < len(lines):
        m = CALLOUT_RE.match(lines[i]) if kinds[i] == "text" else None
        if not m:
            out.append(lines[i])
            i += 1
            continue
        ind = m.group("ind")
        body = [m.group("rest")]
        i += 1
        while i < len(lines) and kinds[i] == "text":
            q = QUOTE_RE.match(lines[i])
            if q and q.group("ind") == ind:
                body.append(q.group("rest"))
            elif not (lines[i].lstrip().startswith(">") or starts_block(lines[i])):
                body.append(lines[i].strip())      # lazy continuation
            else:
                break
            i += 1
        if out and out[-1].strip():
            out.append("")
        out.append(f"{ind}!!! {m.group('label').lower()}")
        out.extend(f"{ind}    {b}" if b.strip() else "" for b in body)
        count += 1
    return out, count


def normalize_dialect(lines: list[str], kinds: list[str]) -> tuple[list[str], dict[str, int]]:
    """Mechanical CommonMark → Python-Markdown fixes (PLAN §2, transform 6):
    list-item content re-indented to 4 spaces per level, a blank line inserted
    before a top-level list that directly follows a paragraph, and a blank line
    inserted where a block (heading, list, fence, quote, HTML) directly follows a
    table row. GFM ends a table there; Python-Markdown reads the block as a row.
    Also a blank line before a list item that directly follows a later paragraph
    of the previous item: Python-Markdown reads the marker as paragraph text. The
    item is already loose (that paragraph follows a blank line), so the list
    renders with the same spacing."""
    out: list[str] = []
    stats = {"reindented": 0, "blank-before-list": 0, "blank-after-table": 0,
             "blank-between-items": 0}
    stack: list[tuple[int, int]] = []       # (original content column, delta)
    fence_delta: tuple[int, int] | None = None   # (threshold column, delta) inside a fence
    prev = "blank"
    later_para = False      # the current text began after a blank line inside a list

    def delta_for(col: int) -> tuple[int, int]:
        for c, d in reversed(stack):
            if col >= c:
                return c, d
        return 0, 0

    for line, kind in zip(lines, kinds):
        if kind == "fence" and fence_delta is not None:
            thr, d = fence_delta
            new = reindent(line, indent_of(line) + d) if (line.strip() and d and indent_of(line) >= thr) else line
            stats["reindented"] += new != line
            out.append(new)
            if FENCE_OPEN_RE.match(line) and prev == "fence-body":
                fence_delta = None
                prev = "fence"
            else:
                prev = "fence-body"
            continue
        if kind == "blank":
            out.append(line)
            prev = "blank"
            continue
        lead = indent_of(line)
        is_quote = line.lstrip().startswith(">")
        m = None if (kind != "text" or is_quote or HR_RE.match(line)) else LIST_RE.match(line)
        interrupts = bool(m) or kind in ("fence", "html") or is_quote or bool(ATX_RE.match(line)) or bool(HR_RE.match(line))
        in_list = bool(stack)
        if prev == "table" and interrupts:
            out.append("")
            stats["blank-after-table"] += 1
        if prev == "blank" or interrupts:
            while stack and lead < stack[-1][0]:
                stack.pop()
        _c, d = delta_for(lead)
        if m:
            if not in_list and prev == "text":
                out.append("")
                stats["blank-before-list"] += 1
            elif in_list and prev == "text" and later_para:
                out.append("")
                stats["blank-between-items"] += 1
            spaces = len(m.group("sp").expandtabs(4))
            width = len(m.group("mark"))
            content = lead + width + (1 if (not m.group("rest") or spaces > 4) else spaces)
            new_base = lead + d
            stack.append((content, new_base + 4 - content))
        new = reindent(line, lead + d) if d else line
        stats["reindented"] += new != line
        out.append(new)
        if kind == "fence":
            thr, dd = delta_for(lead)
            fence_delta = (thr, dd)
            prev = "fence-open"
            continue
        if m:
            prev = "item"
        elif kind == "text" and TABLE_ROW_RE.match(line):
            prev = "table"
        elif kind == "text" and not ATX_RE.match(line):
            if prev != "text":
                later_para = prev == "blank" and bool(stack)
            prev = "text"
        else:
            prev = "other"
    return out, stats


SHORTCODE_RE = re.compile(r":(?=[+\-\w]+:)")
HTML_TAG_RE = re.compile(r"<[^>\n]*>")


def neutralize_shortcodes(lines: list[str], kinds: list[str]) -> tuple[list[str], int]:
    """Keep `:word:` text literal. The site enables pymdownx.emoji, so prose such
    as `HH:mm:ss` would render `:mm:` as a flag; upstream renders no emoji at all.
    The opening colon of each shortcode-shaped run becomes `&#58;`, outside code
    spans, link destinations, bare URLs and HTML tags."""
    out: list[str] = []
    count = 0
    for line, kind in zip(lines, kinds):
        if kind != "text" or ":" not in line:
            out.append(line)
            continue
        masked = mask_code_spans(line)
        for rx in (LINK_DEST_RE, HTML_TAG_RE, BARE_URL_RE):
            masked = rx.sub(lambda m: "\0" * len(m.group(0)), masked)
        hits = []
        for m in SHORTCODE_RE.finditer(masked):
            end = masked.find(":", m.end())
            if hits and m.start() < hits[-1][1]:
                continue
            hits.append((m.start(), end))
        for start, _end in reversed(hits):
            line = line[:start] + "&#58;" + line[start + 1:]
        count += len(hits)
        out.append(line)
    return out, count


def unescape_table_code_pipes(lines: list[str], kinds: list[str]) -> tuple[list[str], int]:
    """In a table row, `\\|` inside a code span is CommonMark's way to keep the
    pipe from splitting the cell. Python-Markdown already ignores pipes inside
    code spans and would print the backslash, so drop it there."""
    out: list[str] = []
    count = 0
    for line, kind in zip(lines, kinds):
        if kind == "text" and TABLE_ROW_RE.match(line) and "\\|" in line:
            new = CODE_SPAN_RE.sub(lambda m: m.group(0).replace("\\|", "|"), line)
            count += new != line
            line = new
        out.append(line)
    return out, count


OL_ITEM_RE = re.compile(r"^(\d{1,9})[.)][ \t]")


def continue_ordered_lists(lines: list[str], kinds: list[str]) -> tuple[list[str], int]:
    """Python-Markdown ignores an ordered list's start number, so a top-level list
    that resumes after a block (step 3, a table, then step 4) restarts at 1. When
    item n+1 follows item n with only non-heading blocks in between, those blocks
    are indented into item n, so the numbering carries on. Upstream renders the
    same steps as `<ol start="n+1">`."""
    out = list(lines)
    count = 0
    last_n: int | None = None
    gap_start: int | None = None     # first top-level non-list line after item n
    for i, (line, kind) in enumerate(zip(lines, kinds)):
        if not line.strip():        # blank, including blank lines inside a fence
            continue
        top = indent_of(line) == 0
        m = OL_ITEM_RE.match(line) if (kind == "text" and top) else None
        if m:
            n = int(m.group(1))
            if gap_start is not None and last_n is not None and n == last_n + 1:
                for j in range(gap_start, i):
                    if out[j].strip():
                        out[j] = "    " + out[j]
                count += 1
            last_n, gap_start = n, None
            continue
        if not top:
            continue
        if ATX_RE.match(line) or HR_RE.match(line) or (kind == "text" and LIST_RE.match(line)):
            last_n, gap_start = None, None
        elif last_n is not None and gap_start is None:
            gap_start = i
    return out, count


def front_matter(page: Page, commit: str) -> str:
    fm: dict = {"tags": ["HUBzero"], "render_macros": False}
    if page.landing:
        fm["hide"] = ["footer"]
    if page.meta.get("summary"):
        fm["description"] = page.meta["summary"]
    hz = {"upstream": page.source, "commit": commit, "status": page.meta.get("status", "")}
    for key, value in page.meta.items():
        if key != "status":
            hz[key] = value
    fm["hubzero"] = hz
    return "---\n" + yaml.safe_dump(fm, sort_keys=False, allow_unicode=True,
                                     default_flow_style=False, width=4096) + "---\n"


def about_block(config: dict, text: str) -> str:
    """Provenance for the landing page. README.md already ends with an "About the
    documentation" section (writing guide, license, status), so the paragraph joins
    it there; otherwise it gets its own section."""
    commit = config["commit"]
    repo = config["repo"].rstrip("/")
    para = (
        "These pages are the documentation of the [HUBzero](https://hubzero.org) platform. "
        "They were imported into the RCAC documentation from the `docs/` directory of "
        f"the [hubzero-cms repository]({repo}) at commit "
        f"[`{commit[:8]}`]({repo}/tree/{commit}/docs), and the HUBzero team maintains them "
        "here. Like the HUBzero code, they are released under the [MIT License](license.md).\n"
    )
    h2 = [ln for ln in text.split("\n") if ln.startswith("## ")]
    if h2 and h2[-1][3:].strip().lower().startswith("about"):
        return "\n" + para
    return "\n## About this documentation\n\n" + para


@dataclass
class Result:
    files: dict[str, bytes]          # docs-relative path -> bytes (pages and assets)
    nav: str                         # the nav region, markers included
    warnings: list[str]
    stats: dict[str, int]
    unreferenced: list[str]


def convert(model: Model, page: Page, warnings: list[str], stats: dict[str, int],
            assets: set[str]) -> bytes:
    def warn(message: str) -> None:
        warnings.append(f"{page.source}: {message}")

    body = expand_includes(page.body, model.src, warn)
    lines = body.lstrip("\n").split("\n")
    kinds = line_kinds(lines)
    resolver = Resolver(model, page, warn)
    lines = rewrite_links(lines, kinds, resolver)
    lines = rewrite_pages_text(lines, kinds, resolver)
    assets |= resolver.assets
    stats["github-fallback-links"] += resolver.fallbacks
    stats["github-pages-refs"] += resolver.pages_rewrites
    lines, n_ids = add_heading_ids(lines, kinds)
    stats["explicit-heading-ids"] += n_ids
    lines, n_callouts = convert_callouts(lines, kinds)
    stats["callouts"] += n_callouts
    kinds = line_kinds(lines)
    lines, n_codes = neutralize_shortcodes(lines, kinds)
    stats["shortcodes"] += n_codes
    lines, n_pipes = unescape_table_code_pipes(lines, kinds)
    stats["table-code-pipes"] += n_pipes
    lines, dialect = normalize_dialect(lines, kinds)
    for key, value in dialect.items():
        stats[key] += value
    kinds = line_kinds(lines)
    lines, n_resumed = continue_ordered_lists(lines, kinds)
    stats["resumed-lists"] += n_resumed
    text = "\n".join(lines).rstrip("\n") + "\n"
    if page.landing:
        text += about_block(model.config, text)
    return (front_matter(page, model.config["commit"]) + "\n" + text).encode("utf-8")


def q(label: str) -> str:
    return '"' + label.replace("\\", "\\\\").replace('"', '\\"') + '"'


def nav_lines(node: Page, depth: int) -> list[str]:
    pad = "  " * depth
    if not node.children:
        return [f"{pad}- {q(plain_text(node.title))}: {node.output}"]
    lines = [f"{pad}- {q(plain_text(node.title))}:"]
    if node.output:
        lines.append(f"{pad}  - {node.output}")
    for child in node.children:
        lines.extend(nav_lines(child, depth + 1))
    return lines


def build_nav(model: Model) -> str:
    landing = next(p for p in model.roots if p.landing)
    lines = [NAV_BEGIN, f"  - {q(NAV_TITLE)}:", f"    - {landing.output}"]
    for book in model.books:
        if book.book in model.enabled:
            lines.extend(nav_lines(book, 2))
    others = [p for p in model.roots if not p.landing]
    if others:
        lines.append(f"    - {q(ABOUT_GROUP)}:")
        title_of = {e["source"]: e["title"] for e in model.config["root_pages"]}
        for page in others:
            lines.append(f"      - {q(title_of[page.source])}: {page.output}")
    lines.append(NAV_END)
    return "\n".join(lines) + "\n"


def run_import(model: Model) -> Result:
    warnings: list[str] = []
    stats = {"pages": 0, "assets": 0, "github-fallback-links": 0, "github-pages-refs": 0,
             "explicit-heading-ids": 0, "callouts": 0, "reindented": 0, "blank-before-list": 0,
             "blank-after-table": 0, "blank-between-items": 0, "shortcodes": 0,
             "table-code-pipes": 0, "resumed-lists": 0}
    assets: set[str] = set()
    files: dict[str, bytes] = {}
    for page in model.pages():
        files[page.output] = convert(model, page, warnings, stats, assets)
        stats["pages"] += 1
    for asset in sorted(assets):
        files[f"{ASSETS_DIR}/{asset[len('docs/'):]}"] = model.src.read_bytes(asset)
    stats["assets"] = len(assets)
    unreferenced = []
    for book in model.books:
        if book.book in model.enabled:
            prefix = f"docs/{book.book}/"
            for path in sorted(model.src.blobs):
                if (path.startswith(prefix) and not path.lower().endswith(".md")
                        and path not in assets):
                    unreferenced.append(path)
    return Result(files=files, nav=build_nav(model), warnings=warnings, stats=stats,
                  unreferenced=unreferenced)


# =================================================================== mkdocs.yml region


def split_nav_region(text: str) -> tuple[str, str | None, str]:
    """(before, region-or-None, after). Without markers, split before `Contact us`."""
    begin = text.find(NAV_BEGIN + "\n")
    if begin >= 0:
        end = text.find(NAV_END + "\n", begin)
        if end < 0:
            raise ImportError_("mkdocs.yml: hubzero nav begin marker without end marker")
        end += len(NAV_END) + 1
        return text[:begin], text[begin:end], text[end:]
    anchor = text.find(NAV_ANCHOR + "\n")
    if anchor < 0:
        raise ImportError_(f"mkdocs.yml: cannot find {NAV_ANCHOR.strip()!r} to place the nav")
    return text[:anchor], None, text[anchor:]


def write_import(result: Result) -> None:
    for top in (DOCS / PAGES_DIR, DOCS / ASSETS_DIR):
        if top.exists():
            shutil.rmtree(top)
    for rel, data in sorted(result.files.items()):
        path = DOCS / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    text = MKDOCS_YML.read_text(encoding="utf-8")
    before, _region, after = split_nav_region(text)
    MKDOCS_YML.write_text(before + result.nav + after, encoding="utf-8", newline="\n")


# =================================================================== check


class SiteParser(HTMLParser):
    """Collect ids anywhere, and links and images inside <article>."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.ids: set[str] = set()
        self.links: list[str] = []
        self.images: list[tuple[str, str | None]] = []
        self.h2: list[tuple[str, str]] = []
        self.h1: list[str] = []
        self._article = 0
        self._heading: tuple[str, str, list[str]] | None = None

    def handle_starttag(self, tag, attrs):
        a = dict(attrs)
        if a.get("id"):
            self.ids.add(a["id"])
        if tag == "article":
            self._article += 1
        if not self._article:
            return
        if tag == "a" and a.get("href") is not None and "headerlink" not in (a.get("class") or ""):
            self.links.append(a["href"])
        elif tag == "img":
            self.images.append((a.get("src") or "", a.get("alt")))
        elif tag in ("h1", "h2"):
            self._heading = (tag, a.get("id") or "", [])
        elif tag == "a" and self._heading is not None:
            self._heading[2].append("\0")   # permalink anchor: ignore its text

    def handle_endtag(self, tag):
        if tag == "article" and self._article:
            self._article -= 1
        if self._heading is not None and tag == self._heading[0]:
            text = "".join(self._heading[2]).split("\0")[0].strip()
            if tag == "h1":
                self.h1.append(text)
            else:
                self.h2.append((self._heading[1], text))
            self._heading = None

    def handle_data(self, data):
        if self._heading is not None:
            self._heading[2].append(data)


def site_path_for(output: str) -> Path:
    stem = output[:-3]
    if stem.endswith("/index") or stem == "index":
        return SITE / stem.rsplit("index", 1)[0] / "index.html"
    return SITE / stem / "index.html"


def split_front_matter(text: str) -> tuple[dict, str]:
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---\n", 4)
    if end < 0:
        return {}, text
    return yaml.safe_load(text[4:end]) or {}, text[end + 5:]


def run_check(model: Model, result: Result, final: bool) -> list[str]:
    findings: list[str] = []
    find = findings.append

    # R8: a re-import reproduces what is committed, byte for byte.
    on_disk: dict[str, bytes] = {}
    for top in (DOCS / PAGES_DIR, DOCS / ASSETS_DIR):
        if top.exists():
            for path in sorted(top.rglob("*")):
                if path.is_file():
                    on_disk[path.relative_to(DOCS).as_posix()] = path.read_bytes()
    for rel in sorted(set(result.files) | set(on_disk)):
        if rel not in on_disk:
            find(f"R8 docs/{rel}: missing; run `import_docs.py import`")
        elif rel not in result.files:
            find(f"R8 docs/{rel}: not produced by the importer (hand-added or stale)")
        elif on_disk[rel] != result.files[rel]:
            find(f"R8 docs/{rel}: differs from a re-import (hand-edited, or importer changed)")
    _b, region, _a = split_nav_region(MKDOCS_YML.read_text(encoding="utf-8"))
    if region != result.nav:
        find("R8 mkdocs.yml: hubzero nav region differs from a re-import")

    # R2: every published source page maps to exactly one output with the same title.
    pages = model.pages()
    pages_host = model.config.get("pages_url", "").split("://", 1)[-1].split("/", 1)[0].lower()
    expected = len(model.roots) + sum(1 for b in model.books if b.book in model.enabled
                                      for p in b.walk() if p.source)
    if len(pages) != expected:
        find(f"R2 page count {len(pages)} != expected {expected}")
    if final:
        if sorted(model.enabled) != sorted(b.book for b in model.books):
            find("R2 --final: not every book is enabled in import.yml")
        if len(pages) != 416:
            find(f"R2 --final: {len(pages)} pages, expected 416")
    for page in pages:
        data = on_disk.get(page.output)
        if data is None:
            continue
        meta, body = split_front_matter(data.decode("utf-8"))
        h1 = next((ln[2:].strip() for ln in body.splitlines() if ln.startswith("# ")), None)
        if h1 != page.title:
            find(f"R2 docs/{page.output}: H1 {h1!r} != source title {page.title!r} ({page.source})")
        # R6/R7: front-matter records status and provenance; the header comment is gone.
        hz = meta.get("hubzero") if isinstance(meta, dict) else None
        if not isinstance(hz, dict) or not all(k in hz for k in ("upstream", "commit", "status")):
            find(f"R6 docs/{page.output}: front-matter lacks hubzero.upstream/commit/status")
        elif hz["upstream"] != page.source or hz["commit"] != model.config["commit"]:
            find(f"R6 docs/{page.output}: hubzero.upstream/commit do not match the source")
        if meta.get("render_macros") is not False:
            find(f"R6 docs/{page.output}: render_macros: false is missing")
        if page.header and page.header.strip() in body:
            find(f"R7 docs/{page.output}: the source metadata header leaks into the body")
        if pages_host and pages_host in body.lower():
            find(f"R12 docs/{page.output}: still references {pages_host}")
        if final and re.search(r"github\.com/hubzero/hubzero-cms/blob/[0-9a-f]{40}/docs/[^)\s\"'#]*\.md", body):
            find(f"R3 --final docs/{page.output}: still links a docs page on GitHub")

    # R1 (final): the landing page links every book's index relatively.
    if final:
        landing = next((pg for pg in pages if pg.landing), None)
        data = on_disk.get(landing.output) if landing else None
        body = split_front_matter(data.decode("utf-8"))[1] if data else ""
        for book in model.books:
            if not re.search(r"\]\(" + re.escape(book.book) + r"/index\.md[)#]", body):
                find(f"R1 --final docs/hubzero/index.md: no relative link to {book.book}/index.md")

    # R11 (final): the home page card.
    if final and "hubzero/index.md" not in (DOCS / "index.md").read_text(encoding="utf-8"):
        find("R11 docs/index.md: no HUBzero card linking hubzero/index.md")

    # Built-site checks: R3 links and anchors, R4 images and alt, R5 API endpoints.
    if not (SITE / PAGES_DIR).is_dir():
        find("R3 site/hubzero/ missing: run `mkdocs build` before `check`")
        return findings
    parsed: dict[Path, SiteParser] = {}

    def parse(path: Path) -> SiteParser | None:
        if path not in parsed:
            if not path.is_file():
                return None
            parser = SiteParser()
            parser.feed(path.read_text(encoding="utf-8"))
            parsed[path] = parser
        return parsed[path]

    for page in pages:
        html_path = site_path_for(page.output)
        doc = parse(html_path)
        if doc is None:
            find(f"R2 {html_path.relative_to(ROOT)}: not built")
            continue
        where = html_path.relative_to(ROOT).as_posix()
        for href in doc.links:
            if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", href) or href.startswith("//"):
                continue
            path_part, _, fragment = href.partition("#")
            path_part = unquote(path_part.split("?", 1)[0])
            if not path_part:
                target = html_path
            elif path_part.startswith("/"):
                target = SITE / path_part.lstrip("/")
            else:
                target = (html_path.parent / path_part).resolve()
            if target.is_dir() or path_part.endswith("/"):
                target = target / "index.html"
            if not target.exists():
                find(f"R3 {where}: link {href!r} does not resolve")
                continue
            if fragment and target.suffix == ".html":
                other = parse(target)
                if other is not None and unquote(fragment) not in other.ids:
                    find(f"R3 {where}: anchor {href!r} does not exist")
        for src_attr, alt in doc.images:
            if not alt or not alt.strip():
                find(f"R4 {where}: image {src_attr!r} has no alt text")
            if re.match(r"^[a-zA-Z][a-zA-Z0-9+.-]*:", src_attr) or src_attr.startswith("//"):
                continue
            target = (SITE / src_attr.lstrip("/")) if src_attr.startswith("/") else (html_path.parent / src_attr).resolve()
            if not target.is_file():
                find(f"R4 {where}: image {src_attr!r} does not exist")
        if page.source and page.source.startswith("docs/reference/api/"):
            want = source_endpoints(page.body)
            rendered = [(hid, text) for hid, text in doc.h2
                        if text.split(" ", 1)[0] in HTTP_METHODS]
            if len(rendered) != len(want):
                find(f"R5 {where}: {len(rendered)} endpoint h2s rendered, source has {len(want)}")
            have = {text: hid for hid, text in rendered}
            params = site_endpoint_params(html_path.read_text(encoding="utf-8"))
            for endpoint, names in want.items():
                hid = have.get(endpoint)
                if hid is None:
                    find(f"R5 {where}: endpoint {endpoint!r} not rendered as an h2 with its full path")
                    continue
                if hid != slugify(endpoint):
                    find(f"R5 {where}: endpoint {endpoint!r} has id {hid!r}, upstream {slugify(endpoint)!r}")
                if params.get(hid, []) != names:
                    find(f"R5 {where}: endpoint {endpoint!r} parameters {params.get(hid, [])} != source {names}")
    return findings


ENDPOINT_PARAM_RE = re.compile(r"^\|\s*`([^`]+)`\s*\|")


def source_endpoints(body: str) -> dict[str, list[str]]:
    """Each `## METHOD /path` heading in a reference/api source page, with the
    parameter names (first column of its Parameter table) in source order."""
    endpoints: dict[str, list[str]] = {}
    current: list[str] | None = None
    in_params = False
    for line in body.splitlines():
        if line.startswith("## "):
            text = line[3:].strip()
            current = endpoints.setdefault(text, []) if text.split(" ", 1)[0] in HTTP_METHODS else None
            in_params = False
        elif current is not None and re.match(r"^\|\s*Parameter\s*\|", line):
            in_params = True
        elif in_params and line.startswith("|"):
            m = ENDPOINT_PARAM_RE.match(line)
            if m:
                current.append(m.group(1))
        elif in_params and not line.strip():
            in_params = False
    return endpoints


def site_endpoint_params(html_text: str) -> dict[str, list[str]]:
    """Built-page counterpart of source_endpoints: h2 id -> the <code> names in the
    first cell of each row of the Parameter table that follows it."""
    out: dict[str, list[str]] = {}
    parts = re.split(r'<h2 id="([^"]*)"', html_text)
    for hid, section in zip(parts[1::2], parts[2::2]):
        table = re.search(r"(?s)<table>\s*<thead>\s*<tr>\s*<th[^>]*>Parameter</th>.*?</table>", section)
        names: list[str] = []
        if table:
            for row in re.findall(r"(?s)<tr>(.*?)</tr>", table.group(0)):
                m = re.match(r"\s*<td[^>]*><code>(.*?)</code>", row)
                if m:
                    names.append(html.unescape(m.group(1)))
        out[hid] = names
    return out


# =================================================================== main


def load_model() -> Model:
    config = yaml.safe_load(CONFIG.read_text(encoding="utf-8"))
    repo = os.environ.get("HUBZERO_CMS")
    if not repo:
        raise ImportError_("set HUBZERO_CMS to a local clone of " + config["repo"])
    return build_model(config, Source(Path(repo).expanduser(), config["commit"]))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    sub.add_parser("import", help="regenerate docs/hubzero/, its images, and the nav region")
    check = sub.add_parser("check", help="acceptance gate: re-import, compare, and check site/")
    check.add_argument("--final", action="store_true",
                       help="also require all five books, 416 pages, and the home-page card")
    args = parser.parse_args(argv)
    try:
        model = load_model()
        result = run_import(model)
    except ImportError_ as exc:
        print(f"import_docs: {exc}", file=sys.stderr)
        return 2
    if args.command == "import":
        write_import(result)
        s = result.stats
        print(f"Imported {s['pages']} pages and {s['assets']} assets from {model.config['commit'][:8]} "
              f"(books: {', '.join(model.enabled) or 'none'}).")
        print(f"  explicit heading ids: {s['explicit-heading-ids']}; callouts: {s['callouts']}; "
              f"list lines re-indented: "
              f"{s['reindented']}; blank lines before lists: {s['blank-before-list']}; "
              f"blank lines after tables: {s['blank-after-table']}; "
              f"blank lines between list items: {s['blank-between-items']}; "
              f"shortcodes kept literal: {s['shortcodes']}; table code pipes: "
              f"{s['table-code-pipes']}; resumed ordered lists: {s['resumed-lists']}; "
              f"links to not-yet-imported pages (GitHub): {s['github-fallback-links']}; "
              f"GitHub Pages references repointed: {s['github-pages-refs']}")
        if result.unreferenced:
            print(f"  {len(result.unreferenced)} unreferenced files in enabled books (not copied):")
            for path in result.unreferenced:
                print(f"    {path}")
        for warning in result.warnings:
            print(f"  warning: {warning}")
        print("Next: .venv/bin/python tools/generate_breadcrumbs.py")
        return 0
    findings = run_check(model, result, args.final)
    for warning in result.warnings:
        print(f"note: {warning}")
    if findings:
        for finding in findings:
            print(f"FAIL {finding}")
        print(f"check: {len(findings)} finding(s)")
        return 1
    print(f"check: PASS ({len(model.pages())} pages; books: {', '.join(model.enabled) or 'none'})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
