-- -*- lua -*---
-- vcftools@0.1.14%gcc@11.2.0 arch=linux-centos8-zen3/2xma37e
--

whatis([[Name : vcftools]])
whatis([[Version : 0.1.14]])
whatis([[Short description : VCFtools is a program package designed for working with VCF files, such as those generated by the 1000 Genomes Project. The aim of VCFtools is to provide easily accessible methods for working with complex genetic variation data in the form of VCF files. ]])
whatis([[Configure options : --with-pmdir=/apps/spack/anvil/apps/vcftools/0.1.14-gcc-11.2.0-2xma37e/lib]])

help([[VCFtools is a program package designed for working with VCF files, such
as those generated by the 1000 Genomes Project. The aim of VCFtools is
to provide easily accessible methods for working with complex genetic
variation data in the form of VCF files.]])


depends_on("zlib/1.2.11")

local modroot="/apps/spack/anvil/apps/vcftools/0.1.14-gcc-11.2.0-2xma37e"
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("MANPATH", modroot.."/share/man", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/", ":")
prepend_path("PERL5LIB", modroot.."/lib", ":")
setenv("VCFTOOLS_HOME", modroot)
setenv("RCAC_VCFTOOLS_ROOT", modroot)
setenv("RCAC_VCFTOOLS_VERSION", "0.1.14")

