-- -*- lua -*---
-- ninja@1.12.1%gcc@11.4.1+re2c build_system=generic arch=linux-rocky9-zen4/a5ol3op
--

whatis([[Name : ninja]])
whatis([[Version : 1.12.1]])
whatis([[Short description : Ninja is a small build system with a focus on speed. It differs from other build systems in two major respects: it is designed to have its input files generated by a higher-level build system, and it is designed to run builds as fast as possible.]])

help([[Ninja is a small build system with a focus on speed. It differs from
other build systems in two major respects: it is designed to have its
input files generated by a higher-level build system, and it is designed
to run builds as fast as possible.]])


depends_on("gcc-runtime/11.4.1-7hex6dy")
depends_on("glibc/2.34-nuyxhw7")

local modroot="/apps/spack/gautschi-cpu/apps/ninja/1.12.1-gcc-11.4.1-a5ol3op"
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/.", ":")
prepend_path("PYTHONPATH", modroot.."/misc", ":")
setenv("NINJA_HOME", modroot)
setenv("RCAC_NINJA_ROOT", modroot)
setenv("RCAC_NINJA_VERSION", modroot)

