-- -*- lua -*---
-- openfoam@2312%gcc@11.4.1~int64~kahip~knl+metis+mgridgen+paraview+scotch+source~vtk~zoltan build_system=generic precision=dp arch=linux-rocky9-zen4/qxeiz3m
--

whatis([[Name : openfoam]])
whatis([[Version : 2312]])
whatis([[Short description : OpenFOAM is a GPL-opensource C++ CFD-toolbox. This offering is supported by OpenCFD Ltd, producer and distributor of the OpenFOAM software via www.openfoam.com, and owner of the OPENFOAM trademark. OpenCFD Ltd has been developing and releasing OpenFOAM since its debut in 2004. ]])

help([[OpenFOAM is a GPL-opensource C++ CFD-toolbox. This offering is supported
by OpenCFD Ltd, producer and distributor of the OpenFOAM software via
www.openfoam.com, and owner of the OPENFOAM trademark. OpenCFD Ltd has
been developing and releasing OpenFOAM since its debut in 2004.]])


depends_on("fftw/3.3.10")
depends_on("openmpi/5.0.5")
depends_on("paraview/5.13.0")

local modroot="/apps/spack/gautschi-cpu/apps/openfoam/2312-gcc-11.4.1-qxeiz3m"
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/.", ":")
prepend_path("ADIOS2_ARCH_PATH", "/apps/spack/gautschi-cpu/apps/adios2/2.10.1-gcc-11.4.1-e2ngtp7", ":")
prepend_path("BOOST_ARCH_PATH", "/apps/spack/gautschi-cpu/apps/boost/1.86.0-gcc-11.4.1-kpkvtzz", ":")
prepend_path("CGAL_ARCH_PATH", "/apps/spack/gautschi-cpu/apps/cgal/5.6-gcc-11.4.1-x2unqki", ":")
prepend_path("FFTW_ARCH_PATH", "/apps/spack/gautschi-cpu/apps/fftw/3.3.10-gcc-11.4.1-62imyak", ":")
setenv("FOAM_API", "2312")
setenv("FOAM_APP", modroot.."/applications")
setenv("FOAM_APPBIN", modroot.."/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_ETC", modroot.."/etc")
setenv("FOAM_LIBBIN", modroot.."/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_MPI", "user-mpi")
setenv("FOAM_RUN", "/home/rcactest/OpenFOAM/rcactest-v2312/run")
setenv("FOAM_SITE_APPBIN", modroot.."/site/2312/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_SITE_LIBBIN", modroot.."/site/2312/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_SOLVERS", modroot.."/applications/solvers")
setenv("FOAM_SRC", modroot.."/src")
setenv("FOAM_TUTORIALS", modroot.."/tutorials")
setenv("FOAM_USER_APPBIN", "/home/rcactest/OpenFOAM/rcactest-v2312/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_USER_LIBBIN", "/home/rcactest/OpenFOAM/rcactest-v2312/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_UTILITIES", modroot.."/applications/utilities")
prepend_path("MPFR_ARCH_PATH", "/apps/spack/gautschi-cpu/apps/mpfr/4.2.1-gcc-11.4.1-zaql3ll", ":")
prepend_path("PV_PLUGIN_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib/paraview-5.13", ":")
setenv("ParaView_INCLUDE_DIR", "/apps/spack/gautschi-cpu/apps/paraview/5.13.0-gcc-11.4.1-onhw76y/include/paraview-5.13")
prepend_path("SCOTCH_ARCH_PATH", "/apps/spack/gautschi-cpu/apps/scotch/7.0.4-gcc-11.4.1-ndgjhqf", ":")
setenv("SCOTCH_VERSION", "scotch-7.0.4")
setenv("WM_ARCH", "linux64")
setenv("WM_COMPILER", "Gcc")
setenv("WM_COMPILER_LIB_ARCH", "64")
setenv("WM_COMPILER_TYPE", "system")
setenv("WM_COMPILE_OPTION", "-spack")
setenv("WM_DIR", modroot.."/wmake")
setenv("WM_LABEL_OPTION", "Int32")
setenv("WM_LABEL_SIZE", "32")
setenv("WM_MPLIB", "USERMPI")
setenv("WM_OPTIONS", "linux64GccDPInt32-spack")
setenv("WM_PRECISION_OPTION", "DP")
setenv("WM_PROJECT", "OpenFOAM")
setenv("WM_PROJECT_DIR", modroot)
setenv("WM_PROJECT_USER_DIR", "/home/rcactest/OpenFOAM/rcactest-v2312")
setenv("WM_PROJECT_VERSION", "v2312")
setenv("WM_THIRD_PARTY_DIR", modroot.."/ThirdParty")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib/dummy", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/gautschi-cpu/apps/adios2/2.10.1-gcc-11.4.1-e2ngtp7/lib64", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/gautschi-cpu/apps/mpfr/4.2.1-gcc-11.4.1-zaql3ll/lib", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/gautschi-cpu/apps/cgal/5.6-gcc-11.4.1-x2unqki/lib64", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/gautschi-cpu/apps/boost/1.86.0-gcc-11.4.1-kpkvtzz/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib/user-mpi", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/site/2312/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("LD_LIBRARY_PATH", "/home/rcactest/OpenFOAM/rcactest-v2312/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("MANPATH", modroot.."/doc", ":")
prepend_path("PATH", "/apps/spack/gautschi-cpu/apps/adios2/2.10.1-gcc-11.4.1-e2ngtp7/bin:/apps/spack/gautschi-cpu/apps/paraview/5.13.0-gcc-11.4.1-onhw76y/bin:/home/rcactest/OpenFOAM/rcactest-v2312/platforms/linux64GccDPInt32-spack/bin:"..modroot.."/site/2312/platforms/linux64GccDPInt32-spack/bin:"..modroot.."/platforms/linux64GccDPInt32-spack/bin:"..modroot.."/bin:"..modroot.."/wmake:/apps/spack/gautschi-cpu/apps/scotch/7.0.4-gcc-11.4.1-ndgjhqf/bin:/apps/spack/gautschi-cpu/apps/parmgridgen/1.0-gcc-11.4.1-tbclbe7/bin:/apps/spack/gautschi-cpu/apps/perl/5.40.0-gcc-11.4.1-cfecsu6/bin:/apps/spack/gautschi-cpu/apps/py-fonttools/4.39.4-gcc-11.4.1-4xewsm3/bin:/apps/spack/gautschi-cpu/apps/py-numpy/1.26.4-gcc-11.4.1-nczxsdn/bin:/apps/spack/gautschi-cpu/apps/py-pybind11/2.13.4-gcc-11.4.1-aveg2jp/bin:/apps/spack/gautschi-cpu/apps/python-venv/1.0-gcc-11.4.1-qysipu4/bin:/apps/spack/gautschi-cpu/apps/python/3.11.9-gcc-11.4.1-6buxgeg/bin:/apps/spack/gautschi-cpu/apps/tcl/8.6.12-gcc-11.4.1-tsav7uj/bin:/apps/spack/gautschi-cpu/apps/sqlite/3.46.0-gcc-11.4.1-lsrvipd/bin:/apps/spack/gautschi-cpu/apps/netcdf-c/4.9.2-gcc-11.4.1-7g7w3za/.spack/spack-nc-config:/apps/spack/gautschi-cpu/apps/pkgconf/2.2.0-gcc-11.4.1-gkykulf/bin:/apps/spack/gautschi-cpu/apps/unzip/6.0-gcc-11.4.1-rhtkoy3/bin:/apps/spack/gautschi-cpu/apps/curl/8.8.0-gcc-11.4.1-qfg7usf/bin:/apps/spack/gautschi-cpu/apps/metis/5.1.0-gcc-11.4.1-7pbwbr6/bin:/apps/spack/gautschi-cpu/apps/m4/1.4.19-gcc-11.4.1-64tpo7u/bin:/apps/spack/gautschi-cpu/apps/flex/2.6.4-gcc-11.4.1-ax4l5gy/bin:/apps/spack/gautschi-cpu/apps/fftw/3.3.10-gcc-11.4.1-62imyak/bin:/apps/spack/gautschi-cpu/apps/cmake/3.23.5-gcc-11.4.1-4bkki2u/bin:/apps/spack/gautschi-cpu/apps/cgal/5.6-gcc-11.4.1-x2unqki/bin:/apps/spack/gautschi-cpu/apps/openmpi/5.0.5-gcc-11.4.1-pso4ah3/bin:/apps/spack/gautschi-cpu/apps/openssh/9.8p1-gcc-11.4.1-ygjytf7/bin:/apps/spack/gautschi-cpu/apps/tar/1.34-gcc-11.4.1-aowtn2c/bin:/apps/spack/gautschi-cpu/apps/pigz/2.8-gcc-11.4.1-incmrxj/bin:/apps/spack/gautschi-cpu/apps/xz/5.4.6-gcc-11.4.1-ifu5mzk/bin:/apps/spack/gautschi-cpu/apps/zstd/1.5.6-gcc-11.4.1-ctqxjhr/bin:/apps/spack/gautschi-cpu/apps/bzip2/1.0.8-gcc-11.4.1-74lbk3j/bin:/apps/spack/gautschi-cpu/framework/spack/lib/spack/env/gcc:/apps/spack/gautschi-cpu/framework/spack/lib/spack/env/case-insensitive:/apps/spack/gautschi-cpu/framework/spack/lib/spack/env:/apps/spack/gautschi-cpu/framework/spack/bin:/apps/spack/gautschi-cpu/apps/openmpi/5.0.5-gcc-14.1.0-wfay46k/bin:/apps/spack/gautschi-cpu/apps/gcc/14.1.0-gcc-11.4.1-fa2732i/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/hpss/bin:/opt/hsi/bin:/opt/puppetlabs/bin:/usr/site/rcac/sbin:/usr/site/rcac/bin:/usr/site/rcac/scripts:/opt/thinlinc/bin:/opt/thinlinc/sbin", ":")
setenv("OPENFOAM_HOME", modroot)
setenv("RCAC_OPENFOAM_ROOT", modroot)
setenv("RCAC_OPENFOAM_VERSION", modroot)
