-- -*- lua -*---
-- paraview@5.12.1-xdmf%gcc@8.5.0~advanced_debug~cuda~examples+hdf5~ipo+kits+mpi+opengl2~osmesa+plugins~python+python3+qt+shared+xdmf build_system=cmake build_type=RelWithDebInfo patches=02253c7 arch=linux-rocky8-zen/houp5w4
--

whatis([[Name : paraview]])
whatis([[Version : 5.12.1-xdmf]])
whatis([[Short description : ParaView is an open-source, multi-platform data analysis and visualization application.]])
whatis([[Configure options : -DVTK_OPENGL_HAS_OSMESA:BOOL=OFF -DVTK_USE_X:BOOL=ON -DPARAVIEW_INSTALL_DEVELOPMENT_FILES:BOOL=ON -DBUILD_TESTING:BOOL=OFF -DOpenGL_GL_PREFERENCE:STRING=LEGACY -DPARAVIEW_INITIALIZE_MPI_ON_CLIENT=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_fast_float:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_token:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_verdict:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_ioss:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_exprtk:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_fmt:BOOL=OFF -DPARAVIEW_USE_QT:BOOL=ON -DPARAVIEW_BUILD_WITH_EXTERNAL=ON -DPARAVIEW_ENABLE_XDMF2:BOOL=OFF -DPARAVIEW_ENABLE_XDMF3:BOOL=ON -DPARAVIEW_USE_VTKM:BOOL=OFF -DPARAVIEW_ENABLE_EXAMPLES:BOOL=OFF -DVTK_MODULE_USE_EXTERNAL_ParaView_cgns=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_glew=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_gl2ps=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_libharu=OFF -DVTK_MODULE_USE_EXTERNAL_VTK_utf8=OFF -DPARAVIEW_QT_VERSION=5 -DPARAVIEW_USE_PYTHON:BOOL=ON -DPYTHON_EXECUTABLE:FILEPATH=/apps/spack/negishi/apps/python/3.9.15-gcc-8.5.0-rqak3rr/bin/python3.9 -DPARAVIEW_PYTHON_VERSION:STRING=3 -DPARAVIEW_USE_MPI:BOOL=ON -DMPIEXEC:FILEPATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-8.5.0-6cqttx3/bin/mpiexec -DMPI_CXX_COMPILER:PATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-8.5.0-6cqttx3/bin/mpic++ -DMPI_C_COMPILER:PATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-8.5.0-6cqttx3/bin/mpicc -DMPI_Fortran_COMPILER:PATH=/apps/spack/negishi/apps/openmpi/4.1.4-gcc-8.5.0-6cqttx3/bin/mpif90 -DPARAVIEW_BUILD_SHARED_LIBS:BOOL=ON -DPARAVIEW_USE_CUDA:BOOL=OFF -DPARAVIEW_BUILD_WITH_KITS:BOOL=ON -DCMAKE_INSTALL_RPATH=/apps/spack/negishi/apps/paraview/5.12.1-xdmf-gcc-8.5.0-houp5w4/lib:/apps/spack/negishi/apps/paraview/5.12.1-xdmf-gcc-8.5.0-houp5w4/lib64:/apps/spack/negishi/apps/bzip2/1.0.8-gcc-8.5.0-zagcjtg/lib:/apps/spack/negishi/apps/expat/2.4.8-gcc-8.5.0-ja6q4u5/lib:/apps/spack/negishi/apps/freetype/2.7.1-gcc-8.5.0-kp75ecc/lib:/apps/spack/negishi/apps/hdf5/1.13.2-gcc-8.5.0-glyvooq/lib:/apps/spack/negishi/apps/libogg/1.3.5-gcc-8.5.0-ebrlla3/lib:/apps/spack/negishi/apps/libpng/1.6.37-gcc-8.5.0-zohhmhy/lib:/apps/spack/negishi/apps/libtheora/1.1.1-gcc-8.5.0-wzde2lu/lib:/apps/spack/negishi/apps/libxml2/2.10.1-gcc-8.5.0-eaerq3s/lib:/apps/spack/negishi/apps/libxt/1.1.5-gcc-8.5.0-km2v3rt/lib:/apps/spack/negishi/apps/lz4/1.9.4-gcc-8.5.0-n4jpv2c/lib:/apps/spack/negishi/apps/netcdf-c/4.9.0-gcc-8.5.0-lxsvgak/lib:/apps/spack/negishi/apps/openmpi/4.1.4-gcc-8.5.0-6cqttx3/lib:/apps/spack/negishi/apps/proj/8.1.0-gcc-8.5.0-p2wbetu/lib:/apps/spack/negishi/apps/qt/5.15.2-gcc-8.5.0-lpnwytg/lib:/apps/spack/negishi/apps/xdmf3/2019-01-14-gcc-8.5.0-tj7awiu/lib:/apps/spack/negishi/apps/xz/5.2.6-gcc-8.5.0-nlapdcj/lib:/apps/spack/negishi/apps/zlib/1.2.13-gcc-8.5.0-abs3mss/lib:/apps/spack/negishi/apps/cli11/1.9.1-gcc-8.5.0-u5pdnbj/lib64:/apps/spack/negishi/apps/double-conversion/3.1.5-gcc-8.5.0-k53uonb/lib64:/apps/spack/negishi/apps/jsoncpp/1.9.4-gcc-8.5.0-ijgxabj/lib64:/apps/spack/negishi/apps/libjpeg-turbo/2.1.3-gcc-8.5.0-ie3b5ki/lib64:/apps/spack/negishi/apps/libtiff/4.4.0-gcc-8.5.0-77cj3zk/lib64:/apps/spack/negishi/apps/protobuf/3.18.0-gcc-8.5.0-lor3bxw/lib64:/apps/spack/negishi/apps/pugixml/1.11.4-gcc-8.5.0-cqeit4i/lib64:/apps/spack/negishi/apps/xdmf3/2019-01-14-gcc-8.5.0-tj7awiu/lib64:/apps/spack/negishi/apps/python/3.9.15-gcc-8.5.0-rqak3rr/lib]])

help([[ParaView is an open-source, multi-platform data analysis and
visualization application.]])


depends_on("bzip2/1.0.8")
depends_on("eigen/3.3.9")
depends_on("hdf5/1.13.2")
depends_on("libtiff/4.4.0")
depends_on("libxml2/2.10.1")
depends_on("netcdf-c/4.9.0")
depends_on("openmpi/4.1.4")
depends_on("proj/8.1.0")
depends_on("protobuf/3.18.0")
depends_on("qt/5.15.2")
depends_on("zlib/1.2.13")

local modroot="/apps/spack/negishi/apps/paraview/5.12.1-xdmf-gcc-8.5.0-houp5w4"
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib", ":")
prepend_path("LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("CPATH", modroot.."/include", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/", ":")
prepend_path("PATH", modroot.."/./bin", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/./", ":")
prepend_path("XLOCALEDIR", "/apps/spack/negishi/apps/libx11/1.7.0-gcc-8.5.0-fahe2ia/share/X11/locale", ":")
prepend_path("TCLLIBPATH", "/apps/spack/negishi/apps/tk/8.6.11-gcc-8.5.0-pq7fdff/lib", " ")
setenv("PROJ_LIB", "/apps/spack/negishi/apps/proj/8.1.0-gcc-8.5.0-p2wbetu/share/proj")
prepend_path("PYTHONPATH", modroot.."/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-matplotlib/3.6.2-gcc-8.5.0-ooc7mjg/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-contourpy/1.0.5-gcc-8.5.0-n4ls4z4/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-numpy/1.23.4-gcc-8.5.0-hn4xyvt/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-setuptools/50.3.2-gcc-8.5.0-fa4avvs/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-cycler/0.11.0-gcc-8.5.0-ocpfbml/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-fonttools/4.37.3-gcc-8.5.0-jqt6vak/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-kiwisolver/1.3.2-gcc-8.5.0-yli6iap/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-packaging/21.3-gcc-8.5.0-vyrvwzl/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-pyparsing/3.0.9-gcc-8.5.0-luntx3z/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-pillow/9.2.0-gcc-8.5.0-dclt6vh/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-python-dateutil/2.8.2-gcc-8.5.0-uk63tsn/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-six/1.16.0-gcc-8.5.0-u7m54sa/lib/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", "/apps/spack/negishi/apps/py-mpi4py/3.1.4-gcc-8.5.0-zuagj77/lib/python3.9/site-packages", ":")
prepend_path("XDG_DATA_DIRS", "/apps/spack/negishi/apps/gobject-introspection/1.72.0-gcc-8.5.0-4ewf4pi/share", ":")
prepend_path("GI_TYPELIB_PATH", "/apps/spack/negishi/apps/gobject-introspection/1.72.0-gcc-8.5.0-4ewf4pi/lib/girepository-1.0", ":")
prepend_path("XDG_DATA_DIRS", "/apps/spack/negishi/apps/harfbuzz/5.1.0-gcc-8.5.0-rg5qkaq/share", ":")
prepend_path("GI_TYPELIB_PATH", "/apps/spack/negishi/apps/harfbuzz/5.1.0-gcc-8.5.0-rg5qkaq/lib/girepository-1.0", ":")
setenv("ParaView_DIR", modroot)
setenv("PARAVIEW_VTK_DIR", modroot.."/lib64/cmake/paraview-5.12/vtk")
prepend_path("LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/lib64", ":")
prepend_path("PYTHONPATH", modroot.."/lib64/python3.9/site-packages", ":")
prepend_path("PYTHONPATH", modroot.."/lib64/python3.9/site-packages/vtkmodules", ":")
setenv("PARAVIEW_HOME", modroot)
setenv("RCAC_PARAVIEW_ROOT", modroot)
setenv("RCAC_PARAVIEW_VERSION", "5.12.1-xdmf")

