-- -*- lua -*-
-- Module file created by spack (https://github.com/spack/spack) on 2025-09-11 10:58:28.939459
--
-- openfoam@2412%gcc@14.2.0~int64~kahip~knl+metis+mgridgen~paraview+scotch+source~vtk~zoltan build_system=generic precision=dp arch=linux-rocky8-zen3/li2iibs
--

whatis([[Name : openfoam]])
whatis([[Version : 2412]])
whatis([[Target : zen3]])
whatis([[Short description : OpenFOAM is a GPL-opensource C++ CFD-toolbox. This offering is supported by OpenCFD Ltd, producer and distributor of the OpenFOAM software via www.openfoam.com, and owner of the OPENFOAM trademark. OpenCFD Ltd has been developing and releasing OpenFOAM since its debut in 2004. ]])

help([[Name   : openfoam]])
help([[Version: 2412]])
help([[Target : zen3]])
help()
help([[OpenFOAM is a GPL-opensource C++ CFD-toolbox. This offering is supported
by OpenCFD Ltd, producer and distributor of the OpenFOAM software via
www.openfoam.com, and owner of the OPENFOAM trademark. OpenCFD Ltd has
been developing and releasing OpenFOAM since its debut in 2004.]])

help([[

To ensure all OpenFOAM environment variables are set properly, it is highly recommended to type the following after loading the module. 

	$ source $FOAM_ETC/bashrc

]])

depends_on("openmpi/5.0.5")
local modroot = "/apps/spack/anvil-cpu-2025/apps/openfoam/2412-gcc-14.2.0-li2iibs"
local user = os.getenv("USER")
local userhome = os.getenv("HOME")

prepend_path("PATH", modroot.."/bin", ":")
prepend_path("CMAKE_PREFIX_PATH", modroot.."/.", ":")
prepend_path("ADIOS2_ARCH_PATH", "/apps/spack/anvil-cpu-2025/apps/adios2/2.10.1-gcc-14.2.0-bmca3if", ":")
prepend_path("BOOST_ARCH_PATH", "/apps/spack/anvil-cpu-2025/apps/boost/1.86.0-gcc-14.2.0-6jmfuxb", ":")
prepend_path("CGAL_ARCH_PATH", "/apps/spack/anvil-cpu-2025/apps/cgal/6.0.1-gcc-14.2.0-dclg5rd", ":")
prepend_path("FFTW_ARCH_PATH", "/apps/spack/anvil-cpu-2025/apps/fftw/3.3.10-gcc-14.2.0-wisoauz", ":")
setenv("FOAM_API", "2412")
setenv("FOAM_APP", modroot.."/applications")
setenv("FOAM_APPBIN", modroot.."/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_ETC", modroot.."/etc")
setenv("FOAM_LIBBIN", modroot.."/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_MPI", "user-mpi")
setenv("FOAM_RUN", userhome.."/OpenFOAM/"..user.."-v2412/run")
setenv("FOAM_SITE_APPBIN", modroot.."/site/2412/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_SITE_LIBBIN", modroot.."/site/2412/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_SOLVERS", modroot.."/applications/solvers")
setenv("FOAM_SRC", modroot.."/src")
setenv("FOAM_TUTORIALS", modroot.."/tutorials")
setenv("FOAM_USER_APPBIN", userhome.."/OpenFOAM/"..user.."-v2412/platforms/linux64GccDPInt32-spack/bin")
setenv("FOAM_USER_LIBBIN", userhome.."/OpenFOAM/"..user.."-v2412/platforms/linux64GccDPInt32-spack/lib")
setenv("FOAM_UTILITIES", modroot.."/applications/utilities")
prepend_path("MPFR_ARCH_PATH", "/apps/spack/anvil-cpu-2025/apps/mpfr/4.2.1-gcc-8.4.0-xvyu75c", ":")
prepend_path("SCOTCH_ARCH_PATH", "/apps/spack/anvil-cpu-2025/apps/scotch/7.0.4-gcc-14.2.0-2nvzclc", ":")
setenv("SCOTCH_VERSION", "scotch-7.0.4")
setenv("WM_ARCH", "linux64")
setenv("WM_COMPILER", "Gcc")
setenv("WM_COMPILER_LIB_ARCH", "64")
setenv("WM_COMPILER_TYPE", "system")
setenv("WM_COMPILE_OPTION", "-spack")
setenv("WM_DIR", modroot.."/wmake")
setenv("WM_LABEL_OPTION", "Int32")
setenv("WM_LABEL_SIZE", "32")
setenv("WM_MPLIB", "USERMPI")
setenv("WM_OPTIONS", "linux64GccDPInt32-spack")
setenv("WM_PRECISION_OPTION", "DP")
setenv("WM_PROJECT", "OpenFOAM")
setenv("WM_PROJECT_DIR", modroot)
setenv("WM_PROJECT_USER_DIR", userhome.."/OpenFOAM/"..user.."-v2412")
setenv("WM_PROJECT_VERSION", "v2412")
setenv("WM_THIRD_PARTY_DIR", modroot.."/ThirdParty")
unsetenv("MPI_HOME")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib/dummy", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/anvil-cpu-2025/apps/adios2/2.10.1-gcc-14.2.0-bmca3if/lib64", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/anvil-cpu-2025/apps/mpfr/4.2.1-gcc-8.4.0-xvyu75c/lib", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/anvil-cpu-2025/apps/cgal/6.0.1-gcc-14.2.0-dclg5rd/lib64", ":")
prepend_path("LD_LIBRARY_PATH", "/apps/spack/anvil-cpu-2025/apps/boost/1.86.0-gcc-14.2.0-6jmfuxb/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/platforms/linux64GccDPInt32-spack/lib/user-mpi", ":")
prepend_path("LD_LIBRARY_PATH", modroot.."/site/2412/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("LD_LIBRARY_PATH", userhome.."/OpenFOAM/"..user.."-v2412/platforms/linux64GccDPInt32-spack/lib", ":")
prepend_path("MANPATH", modroot.."/doc", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/adios2/2.10.1-gcc-14.2.0-bmca3if/bin", ":")
prepend_path("PATH", userhome.."/OpenFOAM/"..user.."-v2412/platforms/linux64GccDPInt32-spack/bin", ":")
prepend_path("PATH", modroot.."/site/2412/platforms/linux64GccDPInt32-spack/bin", ":")
prepend_path("PATH", modroot.."/platforms/linux64GccDPInt32-spack/bin", ":")
prepend_path("PATH", modroot.."/bin", ":")
prepend_path("PATH", modroot.."/wmake", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/scotch/7.0.4-gcc-14.2.0-2nvzclc/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/parmgridgen/1.0-gcc-8.4.0-5cjcpkq/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/metis/5.1.0-gcc-14.2.0-wnanqyt/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/m4/1.4.19-gcc-14.2.0-uyr6eij/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/flex/2.6.4-gcc-14.2.0-2sjlgox/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/fftw/3.3.10-gcc-14.2.0-wisoauz/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/cmake/3.30.5-gcc-8.4.0-ncydp5t/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/cgal/6.0.1-gcc-14.2.0-dclg5rd/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/openmpi/5.0.5-gcc-8.4.0-rpgeqcj/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/openssh/9.9p1-gcc-8.4.0-t5kgpdk/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/tar/1.34-gcc-8.4.0-aw2vsoz/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/pigz/2.8-gcc-8.4.0-2q4iclh/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/xz/5.4.6-gcc-8.4.0-u5gmz7a/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/zstd/1.5.6-gcc-8.4.0-bgs3fbc/bin", ":")
prepend_path("PATH", "/apps/spack/anvil-cpu-2025/apps/bzip2/1.0.8-gcc-8.4.0-hho4jem/bin", ":")
setenv("OPENFOAM_HOME", modroot)
setenv("RCAC_OPENFOAM_ROOT", modroot)
setenv("RCAC_OPENFOAM_VERSION", modroot)
append_path("MANPATH", "", ":")
