whatis("Name: converge_cfd")
whatis("Version: 6.0.1")
whatis("Description: Multipurpose computational CFD code.")
whatis("Keywords: CFD")

local appname = "CONVERGE"
local version = "6.0.1"
local modroot = "/apps/external/converge/Convergent_Science/CONVERGE_CFD/"..version

prereq("intel") -- 17.0.1.132
prereq("impi")  -- 2017.1.132

setenv("CONVERGE", modroot.."CONVERGE/x64/bin/converge-intel")
setenv("RLM_LICENSE", "2765@dock.ecn.purdue.edu")
setenv("MPI_TYPE", "INTEL")

prepend_path("PATH", modroot.."/CONVERGE/x64/bin")
prepend_path("PATH", modroot.."/CONVERGE_Studio/x64/bin")
prepend_path("LD_LIBRARY_PATH", modroot.."/CONVERGE/x64/lib64")
prepend_path("LD_LIBRARY_PATH", modroot.."/CONVERGE/x64/lib64/INTEL")

-- envs from intel env script

setenv("BOOST_ROOT","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/include/third_party")
setenv("CARNOT_BANK_FILE","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/data/CarnotBank4Converge.xml")
setenv("CATALYST_IMPLEMENTATION_NAME","paraview")
setenv("CATALYST_IMPLEMENTATION_PATHS","/apps/external/converge/Convergent_Science/ParaView/6.1.0/INTEL/lib64/catalyst")
setenv("CATALYST_LIB","/apps/external/converge/Convergent_Science/catalyst/2.0.0/INTEL/lib64")
setenv("CATALYST_ROOT","/apps/external/converge/Convergent_Science/catalyst/2.0.0/INTEL")
setenv("CONVERGE_ROOT","/apps/external/converge/Convergent_Science")
setenv("CPI_ROOT","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/utilities/x64/cpi")
setenv("CVG_SOLVER_ROOT","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE")
setenv("FFMPEG_LIB","/apps/external/converge/Convergent_Science/ffmpeg/8.1.1/lib")
setenv("FFMPEG_ROOT","/apps/external/converge/Convergent_Science/ffmpeg/8.1.1")
setenv("FI_PROVIDER_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/libfabric/lib/prov")
setenv("I_MPI_ROOT","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL")
setenv("I_MPI_SHM_HEAP_VSIZE","512")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/ffmpeg/8.1.1/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/catalyst/2.0.0/INTEL/lib64")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/python/3.12.11/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/ParaView/mesa/18.3.6/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/ParaView/6.1.0/INTEL/lib64")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/python/3.12.11/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/lib64")
prepend_path("LD_LIBRARY_PATH",".")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/lib/release")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/libfabric/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/ucc/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/ucc/lib/ucc")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/ucx/lib")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/ucx/lib/ucx")
prepend_path("LD_LIBRARY_PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/lib64/INTEL")
prepend_path("MANPATH","/apps/external/converge/Convergent_Science/ffmpeg/8.1.1/manpages")
prepend_path("MANPATH","/apps/external/converge/Convergent_Science/python/3.12.11/share/man")
prepend_path("MANPATH","/apps/external/converge/Convergent_Science/python/3.12.11/share/man")
setenv("MESA_INC","/apps/external/converge/Convergent_Science/ParaView/mesa/18.3.6/include")
setenv("MESA_LIB","/apps/external/converge/Convergent_Science/ParaView/mesa/18.3.6/lib")
setenv("MESA_ROOT","/apps/external/converge/Convergent_Science/ParaView/mesa/18.3.6")
setenv("MPI_TYPE","INTEL")
setenv("MPI_VERSION","2021.14.2")
setenv("OCL_ICD_FILENAMES","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/lib64/libintelocl.so")
prepend_path("PATH","/apps/external/converge/Convergent_Science/ffmpeg/8.1.1/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/catalyst/2.0.0/INTEL/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/python/3.12.11/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/ParaView/6.1.0/INTEL/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/python/3.12.11/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/utilities/x64/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/libfabric/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/ucc/bin")
prepend_path("PATH","/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/CONVERGE/x64/mpi/INTEL/ucx/bin")
prepend_path("PKG_CONFIG_PATH","/apps/external/converge/Convergent_Science/ffmpeg/8.1.1/lib/pkgconfig")
setenv("PYTHONHOME","/apps/external/converge/Convergent_Science/python/3.12.11")
setenv("PYTHONPATH","/apps/external/converge/Convergent_Science/python/3.12.11/lib/python3.12/site-packages:/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/utilities/x64/udf_migration_tool:/apps/external/converge/Convergent_Science/CONVERGE_CFD/6.0.1/utilities/x64/cpi:/apps/external/converge/Convergent_Science/ParaView/6.1.0/INTEL/lib64/python3.12/site-packages:/apps/external/converge/Convergent_Science/python/3.12.11/lib/python3.12/site-packages:/apps/external/converge/Convergent_Science/catalyst/2.0.0/INTEL/lib64/python3.12/site-packages:")
setenv("PYTHON_BIN","/apps/external/converge/Convergent_Science/python/3.12.11/bin")
setenv("PYTHON_INC","/apps/external/converge/Convergent_Science/python/3.12.11/include")
setenv("PYTHON_LIB","/apps/external/converge/Convergent_Science/python/3.12.11/lib")
setenv("PYTHON_ROOT","/apps/external/converge/Convergent_Science/python/3.12.11")
setenv("UCX_MEM_EVENTS","n")
setenv("UCX_TLS","all")
setenv("VTK_SILENCE_GET_VOID_POINTER_WARNINGS","TRUE")
