#!/usr/bin/env python3
"""Generate the per-cluster agentic-AI context and settings files from a data model.

Single source of truth: one small YAML per cluster under
``tools/agent_context/clusters/`` plus the shared Jinja2 templates under
``tools/agent_context/templates/``. This script renders them into the deployable tree
``docs/snippets/agentic-ai/<cluster>/`` (the same files RCAC ships to ``/etc/agents.d``
and the per-harness settings paths), and assembles the concatenated ``AGENTS.md``.

Run from anywhere (paths are resolved relative to this file):

    python tools/generate_agent_context.py

Do NOT hand-edit the generated files under docs/snippets/agentic-ai/<cluster>/ — edit
the cluster YAML or the templates and regenerate. Any literal ``[NEEDS CLARIFICATION]``
left in a cluster YAML aborts generation (override with --allow-incomplete for drafts).
"""
import glob
import os
import shutil
import sys

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
AC_DIR = os.path.join(ROOT_DIR, "tools", "agent_context")
CLUSTERS_DIR = os.path.join(AC_DIR, "clusters")
TEMPLATES_DIR = os.path.join(AC_DIR, "templates")
OUTPUT_ROOT = os.path.join(ROOT_DIR, "docs", "snippets", "agentic-ai")

# Topic files, in the order they are concatenated into AGENTS.md.
TOPIC_FILES = ["unix", "filesystems", "lmod", "slurm", "policies"]

# (template path relative to TEMPLATES_DIR, output path relative to the cluster dir)
CONFIG_TEMPLATES = [
    ("claude/settings.json.j2", "claude/settings.json"),
    ("codex/config.toml.j2", "codex/config.toml"),
    ("gemini/settings.json.j2", "gemini/settings.json"),
    ("opencode/opencode.json.j2", "opencode/opencode.json"),
]

_MARKER = (
    "Note: generated by tools/generate_agent_context.py from "
    "tools/agent_context/clusters/{cluster}.yml. Manual changes will be lost!"
)


def _md_marker(cluster):
    return "<!-- %s -->\n" % _MARKER.format(cluster=cluster)


def _toml_marker(cluster):
    return "# %s\n" % _MARKER.format(cluster=cluster)


def _find_needs_clarification(cluster, data):
    """Return a list of (path, value) where an unresolved marker string survives."""
    found = []

    def walk(value, path):
        if isinstance(value, dict):
            for key, child in value.items():
                walk(child, "%s.%s" % (path, key))
        elif isinstance(value, list):
            for i, child in enumerate(value):
                walk(child, "%s[%d]" % (path, i))
        elif isinstance(value, str) and "[NEEDS CLARIFICATION" in value:
            found.append((path, value))

    walk(data, cluster)
    return found


def _assemble_agents_md(title, bodies):
    """Concatenate topic bodies into the single AGENTS.md, matching the deployed shape."""
    assembled = (
        "# %s Agent Context\n\n"
        "This file is the assembled agent context for Purdue RCAC's **%s**\n"
        "cluster, concatenated from the topic files in `/etc/agents.d/`. It is the\n"
        "canonical guidance an agent should follow when operating on %s. Read it\n"
        "before acting.\n" % (title, title, title)
    )
    for name in TOPIC_FILES:
        assembled += "\n<!-- Source: %s.md -->\n\n" % name + bodies[name]
    return assembled


def main():
    allow_incomplete = "--allow-incomplete" in sys.argv

    env = Environment(
        loader=FileSystemLoader(TEMPLATES_DIR),
        trim_blocks=True,
        lstrip_blocks=True,
        keep_trailing_newline=True,
        undefined=StrictUndefined,
    )

    cluster_files = sorted(glob.glob(os.path.join(CLUSTERS_DIR, "*.yml")))
    if not cluster_files:
        sys.exit("❌ no cluster data files found in %s" % CLUSTERS_DIR)

    generated = []
    for cluster_file in cluster_files:
        with open(cluster_file, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        cluster = data["cluster"]

        incomplete = _find_needs_clarification(cluster, data)
        if incomplete and not allow_incomplete:
            print("❌ %s has unresolved [NEEDS CLARIFICATION]:" % cluster, file=sys.stderr)
            for path, value in incomplete:
                print("     %s: %s" % (path, value), file=sys.stderr)
            sys.exit("Resolve them in %s (or pass --allow-incomplete for a draft)." % cluster_file)

        outdir = os.path.join(OUTPUT_ROOT, cluster)
        # Regenerate the cluster tree from scratch so removed inputs prune cleanly.
        if os.path.isdir(outdir):
            shutil.rmtree(outdir)

        # Render the topic bodies once; reused for the standalone files and AGENTS.md.
        bodies = {
            name: env.get_template("agents.d/%s.md.j2" % name).render(**data)
            for name in TOPIC_FILES
        }

        agents_d = os.path.join(outdir, "agents.d")
        os.makedirs(agents_d, exist_ok=True)
        for name in TOPIC_FILES:
            with open(os.path.join(agents_d, "%s.md" % name), "w", encoding="utf-8") as fh:
                fh.write(_md_marker(cluster) + bodies[name])

        with open(os.path.join(agents_d, "AGENTS.md"), "w", encoding="utf-8") as fh:
            fh.write(_md_marker(cluster) + _assemble_agents_md(data["title"], bodies))

        for tmpl_path, out_path in CONFIG_TEMPLATES:
            rendered = env.get_template(tmpl_path).render(**data)
            if out_path.endswith(".toml"):
                rendered = _toml_marker(cluster) + rendered
            # JSON cannot carry a comment marker; the tree-level GENERATED.md documents it.
            dest = os.path.join(outdir, out_path)
            os.makedirs(os.path.dirname(dest), exist_ok=True)
            with open(dest, "w", encoding="utf-8") as fh:
                fh.write(rendered)

        generated.append(cluster)

    print(
        "✅ generated agentic-AI context for %d cluster(s): %s"
        % (len(generated), ", ".join(generated))
    )


if __name__ == "__main__":
    main()
